// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KlineData.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_KlineData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_KlineData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_KlineData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_KlineData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_KlineData_2eproto;
namespace tigeropen {
namespace push {
namespace pb {
class KlineData;
struct KlineDataDefaultTypeInternal;
extern KlineDataDefaultTypeInternal _KlineData_default_instance_;
}  // namespace pb
}  // namespace push
}  // namespace tigeropen
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace tigeropen {
namespace push {
namespace pb {

// ===================================================================


// -------------------------------------------------------------------

class KlineData final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tigeropen.push.pb.KlineData) */ {
 public:
  inline KlineData() : KlineData(nullptr) {}
  ~KlineData() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR KlineData(::google::protobuf::internal::ConstantInitialized);

  inline KlineData(const KlineData& from)
      : KlineData(nullptr, from) {}
  KlineData(KlineData&& from) noexcept
    : KlineData() {
    *this = ::std::move(from);
  }

  inline KlineData& operator=(const KlineData& from) {
    CopyFrom(from);
    return *this;
  }
  inline KlineData& operator=(KlineData&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KlineData& default_instance() {
    return *internal_default_instance();
  }
  static inline const KlineData* internal_default_instance() {
    return reinterpret_cast<const KlineData*>(
               &_KlineData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(KlineData& a, KlineData& b) {
    a.Swap(&b);
  }
  inline void Swap(KlineData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KlineData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KlineData* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KlineData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const KlineData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const KlineData& from) {
    KlineData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(KlineData* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "tigeropen.push.pb.KlineData";
  }
  protected:
  explicit KlineData(::google::protobuf::Arena* arena);
  KlineData(::google::protobuf::Arena* arena, const KlineData& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSymbolFieldNumber = 9,
    kTimeFieldNumber = 1,
    kOpenFieldNumber = 2,
    kHighFieldNumber = 3,
    kLowFieldNumber = 4,
    kCloseFieldNumber = 5,
    kVolumeFieldNumber = 7,
    kAvgFieldNumber = 6,
    kCountFieldNumber = 8,
    kAmountFieldNumber = 10,
    kServerTimestampFieldNumber = 11,
  };
  // string symbol = 9;
  void clear_symbol() ;
  const std::string& symbol() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_symbol(Arg_&& arg, Args_... args);
  std::string* mutable_symbol();
  PROTOBUF_NODISCARD std::string* release_symbol();
  void set_allocated_symbol(std::string* value);

  private:
  const std::string& _internal_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(
      const std::string& value);
  std::string* _internal_mutable_symbol();

  public:
  // int64 time = 1;
  void clear_time() ;
  ::int64_t time() const;
  void set_time(::int64_t value);

  private:
  ::int64_t _internal_time() const;
  void _internal_set_time(::int64_t value);

  public:
  // float open = 2;
  void clear_open() ;
  float open() const;
  void set_open(float value);

  private:
  float _internal_open() const;
  void _internal_set_open(float value);

  public:
  // float high = 3;
  void clear_high() ;
  float high() const;
  void set_high(float value);

  private:
  float _internal_high() const;
  void _internal_set_high(float value);

  public:
  // float low = 4;
  void clear_low() ;
  float low() const;
  void set_low(float value);

  private:
  float _internal_low() const;
  void _internal_set_low(float value);

  public:
  // float close = 5;
  void clear_close() ;
  float close() const;
  void set_close(float value);

  private:
  float _internal_close() const;
  void _internal_set_close(float value);

  public:
  // int64 volume = 7;
  void clear_volume() ;
  ::int64_t volume() const;
  void set_volume(::int64_t value);

  private:
  ::int64_t _internal_volume() const;
  void _internal_set_volume(::int64_t value);

  public:
  // float avg = 6;
  void clear_avg() ;
  float avg() const;
  void set_avg(float value);

  private:
  float _internal_avg() const;
  void _internal_set_avg(float value);

  public:
  // int32 count = 8;
  void clear_count() ;
  ::int32_t count() const;
  void set_count(::int32_t value);

  private:
  ::int32_t _internal_count() const;
  void _internal_set_count(::int32_t value);

  public:
  // double amount = 10;
  void clear_amount() ;
  double amount() const;
  void set_amount(double value);

  private:
  double _internal_amount() const;
  void _internal_set_amount(double value);

  public:
  // uint64 serverTimestamp = 11;
  void clear_servertimestamp() ;
  ::uint64_t servertimestamp() const;
  void set_servertimestamp(::uint64_t value);

  private:
  ::uint64_t _internal_servertimestamp() const;
  void _internal_set_servertimestamp(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:tigeropen.push.pb.KlineData)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 11, 0,
      50, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr symbol_;
    ::int64_t time_;
    float open_;
    float high_;
    float low_;
    float close_;
    ::int64_t volume_;
    float avg_;
    ::int32_t count_;
    double amount_;
    ::uint64_t servertimestamp_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_KlineData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// KlineData

// int64 time = 1;
inline void KlineData::clear_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.time_ = ::int64_t{0};
}
inline ::int64_t KlineData::time() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.time)
  return _internal_time();
}
inline void KlineData::set_time(::int64_t value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.time)
}
inline ::int64_t KlineData::_internal_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.time_;
}
inline void KlineData::_internal_set_time(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.time_ = value;
}

// float open = 2;
inline void KlineData::clear_open() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.open_ = 0;
}
inline float KlineData::open() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.open)
  return _internal_open();
}
inline void KlineData::set_open(float value) {
  _internal_set_open(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.open)
}
inline float KlineData::_internal_open() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.open_;
}
inline void KlineData::_internal_set_open(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.open_ = value;
}

// float high = 3;
inline void KlineData::clear_high() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.high_ = 0;
}
inline float KlineData::high() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.high)
  return _internal_high();
}
inline void KlineData::set_high(float value) {
  _internal_set_high(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.high)
}
inline float KlineData::_internal_high() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.high_;
}
inline void KlineData::_internal_set_high(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.high_ = value;
}

// float low = 4;
inline void KlineData::clear_low() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.low_ = 0;
}
inline float KlineData::low() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.low)
  return _internal_low();
}
inline void KlineData::set_low(float value) {
  _internal_set_low(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.low)
}
inline float KlineData::_internal_low() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.low_;
}
inline void KlineData::_internal_set_low(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.low_ = value;
}

// float close = 5;
inline void KlineData::clear_close() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.close_ = 0;
}
inline float KlineData::close() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.close)
  return _internal_close();
}
inline void KlineData::set_close(float value) {
  _internal_set_close(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.close)
}
inline float KlineData::_internal_close() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.close_;
}
inline void KlineData::_internal_set_close(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.close_ = value;
}

// float avg = 6;
inline void KlineData::clear_avg() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.avg_ = 0;
}
inline float KlineData::avg() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.avg)
  return _internal_avg();
}
inline void KlineData::set_avg(float value) {
  _internal_set_avg(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.avg)
}
inline float KlineData::_internal_avg() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.avg_;
}
inline void KlineData::_internal_set_avg(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.avg_ = value;
}

// int64 volume = 7;
inline void KlineData::clear_volume() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.volume_ = ::int64_t{0};
}
inline ::int64_t KlineData::volume() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.volume)
  return _internal_volume();
}
inline void KlineData::set_volume(::int64_t value) {
  _internal_set_volume(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.volume)
}
inline ::int64_t KlineData::_internal_volume() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.volume_;
}
inline void KlineData::_internal_set_volume(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.volume_ = value;
}

// int32 count = 8;
inline void KlineData::clear_count() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.count_ = 0;
}
inline ::int32_t KlineData::count() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.count)
  return _internal_count();
}
inline void KlineData::set_count(::int32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.count)
}
inline ::int32_t KlineData::_internal_count() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.count_;
}
inline void KlineData::_internal_set_count(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.count_ = value;
}

// string symbol = 9;
inline void KlineData::clear_symbol() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.symbol_.ClearToEmpty();
}
inline const std::string& KlineData::symbol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.symbol)
  return _internal_symbol();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void KlineData::set_symbol(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.symbol)
}
inline std::string* KlineData::mutable_symbol() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.KlineData.symbol)
  return _s;
}
inline const std::string& KlineData::_internal_symbol() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.symbol_.Get();
}
inline void KlineData::_internal_set_symbol(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.symbol_.Set(value, GetArena());
}
inline std::string* KlineData::_internal_mutable_symbol() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.symbol_.Mutable( GetArena());
}
inline std::string* KlineData::release_symbol() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.KlineData.symbol)
  return _impl_.symbol_.Release();
}
inline void KlineData::set_allocated_symbol(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.symbol_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.symbol_.IsDefault()) {
          _impl_.symbol_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.KlineData.symbol)
}

// double amount = 10;
inline void KlineData::clear_amount() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.amount_ = 0;
}
inline double KlineData::amount() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.amount)
  return _internal_amount();
}
inline void KlineData::set_amount(double value) {
  _internal_set_amount(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.amount)
}
inline double KlineData::_internal_amount() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.amount_;
}
inline void KlineData::_internal_set_amount(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.amount_ = value;
}

// uint64 serverTimestamp = 11;
inline void KlineData::clear_servertimestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.servertimestamp_ = ::uint64_t{0u};
}
inline ::uint64_t KlineData::servertimestamp() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.KlineData.serverTimestamp)
  return _internal_servertimestamp();
}
inline void KlineData::set_servertimestamp(::uint64_t value) {
  _internal_set_servertimestamp(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.KlineData.serverTimestamp)
}
inline ::uint64_t KlineData::_internal_servertimestamp() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.servertimestamp_;
}
inline void KlineData::_internal_set_servertimestamp(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.servertimestamp_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace push
}  // namespace tigeropen


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_KlineData_2eproto_2epb_2eh
