// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderStatusData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_OrderStatusData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_OrderStatusData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_OrderStatusData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_OrderStatusData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_OrderStatusData_2eproto;
namespace tigeropen {
namespace push {
namespace pb {
class OrderStatusData;
struct OrderStatusDataDefaultTypeInternal;
extern OrderStatusDataDefaultTypeInternal _OrderStatusData_default_instance_;
}  // namespace pb
}  // namespace push
}  // namespace tigeropen
PROTOBUF_NAMESPACE_OPEN
template<> ::tigeropen::push::pb::OrderStatusData* Arena::CreateMaybeMessage<::tigeropen::push::pb::OrderStatusData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tigeropen {
namespace push {
namespace pb {

// ===================================================================

class OrderStatusData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tigeropen.push.pb.OrderStatusData) */ {
 public:
  inline OrderStatusData() : OrderStatusData(nullptr) {}
  ~OrderStatusData() override;
  explicit PROTOBUF_CONSTEXPR OrderStatusData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OrderStatusData(const OrderStatusData& from);
  OrderStatusData(OrderStatusData&& from) noexcept
    : OrderStatusData() {
    *this = ::std::move(from);
  }

  inline OrderStatusData& operator=(const OrderStatusData& from) {
    CopyFrom(from);
    return *this;
  }
  inline OrderStatusData& operator=(OrderStatusData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OrderStatusData& default_instance() {
    return *internal_default_instance();
  }
  static inline const OrderStatusData* internal_default_instance() {
    return reinterpret_cast<const OrderStatusData*>(
               &_OrderStatusData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OrderStatusData& a, OrderStatusData& b) {
    a.Swap(&b);
  }
  inline void Swap(OrderStatusData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OrderStatusData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OrderStatusData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OrderStatusData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OrderStatusData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OrderStatusData& from) {
    OrderStatusData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OrderStatusData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tigeropen.push.pb.OrderStatusData";
  }
  protected:
  explicit OrderStatusData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAttrListFieldNumber = 42,
    kAccountFieldNumber = 2,
    kSymbolFieldNumber = 3,
    kExpiryFieldNumber = 4,
    kStrikeFieldNumber = 5,
    kRightFieldNumber = 6,
    kIdentifierFieldNumber = 7,
    kActionFieldNumber = 9,
    kMarketFieldNumber = 10,
    kCurrencyFieldNumber = 11,
    kSegTypeFieldNumber = 12,
    kSecTypeFieldNumber = 13,
    kOrderTypeFieldNumber = 14,
    kStatusFieldNumber = 24,
    kReplaceStatusFieldNumber = 25,
    kCancelStatusFieldNumber = 26,
    kNameFieldNumber = 31,
    kSourceFieldNumber = 32,
    kErrorMsgFieldNumber = 33,
    kAttrDescFieldNumber = 34,
    kUserMarkFieldNumber = 38,
    kIdFieldNumber = 1,
    kMultiplierFieldNumber = 8,
    kTotalQuantityScaleFieldNumber = 17,
    kTotalQuantityFieldNumber = 16,
    kFilledQuantityFieldNumber = 18,
    kAvgFillPriceFieldNumber = 20,
    kLimitPriceFieldNumber = 21,
    kStopPriceFieldNumber = 22,
    kRealizedPnlFieldNumber = 23,
    kFilledQuantityScaleFieldNumber = 19,
    kIsLongFieldNumber = 15,
    kOutsideRthFieldNumber = 27,
    kCanModifyFieldNumber = 28,
    kCanCancelFieldNumber = 29,
    kLiquidationFieldNumber = 30,
    kCommissionAndFeeFieldNumber = 35,
    kOpenTimeFieldNumber = 36,
    kTimestampFieldNumber = 37,
    kTotalCashAmountFieldNumber = 39,
    kFilledCashAmountFieldNumber = 40,
    kGstFieldNumber = 41,
  };
  // repeated string attrList = 42;
  int attrlist_size() const;
  private:
  int _internal_attrlist_size() const;
  public:
  void clear_attrlist();
  const std::string& attrlist(int index) const;
  std::string* mutable_attrlist(int index);
  void set_attrlist(int index, const std::string& value);
  void set_attrlist(int index, std::string&& value);
  void set_attrlist(int index, const char* value);
  void set_attrlist(int index, const char* value, size_t size);
  std::string* add_attrlist();
  void add_attrlist(const std::string& value);
  void add_attrlist(std::string&& value);
  void add_attrlist(const char* value);
  void add_attrlist(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& attrlist() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_attrlist();
  private:
  const std::string& _internal_attrlist(int index) const;
  std::string* _internal_add_attrlist();
  public:

  // string account = 2;
  void clear_account();
  const std::string& account() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account();
  PROTOBUF_NODISCARD std::string* release_account();
  void set_allocated_account(std::string* account);
  private:
  const std::string& _internal_account() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account(const std::string& value);
  std::string* _internal_mutable_account();
  public:

  // string symbol = 3;
  void clear_symbol();
  const std::string& symbol() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_symbol(ArgT0&& arg0, ArgT... args);
  std::string* mutable_symbol();
  PROTOBUF_NODISCARD std::string* release_symbol();
  void set_allocated_symbol(std::string* symbol);
  private:
  const std::string& _internal_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(const std::string& value);
  std::string* _internal_mutable_symbol();
  public:

  // string expiry = 4;
  void clear_expiry();
  const std::string& expiry() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_expiry(ArgT0&& arg0, ArgT... args);
  std::string* mutable_expiry();
  PROTOBUF_NODISCARD std::string* release_expiry();
  void set_allocated_expiry(std::string* expiry);
  private:
  const std::string& _internal_expiry() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_expiry(const std::string& value);
  std::string* _internal_mutable_expiry();
  public:

  // string strike = 5;
  void clear_strike();
  const std::string& strike() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_strike(ArgT0&& arg0, ArgT... args);
  std::string* mutable_strike();
  PROTOBUF_NODISCARD std::string* release_strike();
  void set_allocated_strike(std::string* strike);
  private:
  const std::string& _internal_strike() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_strike(const std::string& value);
  std::string* _internal_mutable_strike();
  public:

  // string right = 6;
  void clear_right();
  const std::string& right() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_right(ArgT0&& arg0, ArgT... args);
  std::string* mutable_right();
  PROTOBUF_NODISCARD std::string* release_right();
  void set_allocated_right(std::string* right);
  private:
  const std::string& _internal_right() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_right(const std::string& value);
  std::string* _internal_mutable_right();
  public:

  // string identifier = 7;
  void clear_identifier();
  const std::string& identifier() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_identifier(ArgT0&& arg0, ArgT... args);
  std::string* mutable_identifier();
  PROTOBUF_NODISCARD std::string* release_identifier();
  void set_allocated_identifier(std::string* identifier);
  private:
  const std::string& _internal_identifier() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_identifier(const std::string& value);
  std::string* _internal_mutable_identifier();
  public:

  // string action = 9;
  void clear_action();
  const std::string& action() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_action(ArgT0&& arg0, ArgT... args);
  std::string* mutable_action();
  PROTOBUF_NODISCARD std::string* release_action();
  void set_allocated_action(std::string* action);
  private:
  const std::string& _internal_action() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_action(const std::string& value);
  std::string* _internal_mutable_action();
  public:

  // string market = 10;
  void clear_market();
  const std::string& market() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_market(ArgT0&& arg0, ArgT... args);
  std::string* mutable_market();
  PROTOBUF_NODISCARD std::string* release_market();
  void set_allocated_market(std::string* market);
  private:
  const std::string& _internal_market() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_market(const std::string& value);
  std::string* _internal_mutable_market();
  public:

  // string currency = 11;
  void clear_currency();
  const std::string& currency() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_currency(ArgT0&& arg0, ArgT... args);
  std::string* mutable_currency();
  PROTOBUF_NODISCARD std::string* release_currency();
  void set_allocated_currency(std::string* currency);
  private:
  const std::string& _internal_currency() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_currency(const std::string& value);
  std::string* _internal_mutable_currency();
  public:

  // string segType = 12;
  void clear_segtype();
  const std::string& segtype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_segtype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_segtype();
  PROTOBUF_NODISCARD std::string* release_segtype();
  void set_allocated_segtype(std::string* segtype);
  private:
  const std::string& _internal_segtype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_segtype(const std::string& value);
  std::string* _internal_mutable_segtype();
  public:

  // string secType = 13;
  void clear_sectype();
  const std::string& sectype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sectype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sectype();
  PROTOBUF_NODISCARD std::string* release_sectype();
  void set_allocated_sectype(std::string* sectype);
  private:
  const std::string& _internal_sectype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sectype(const std::string& value);
  std::string* _internal_mutable_sectype();
  public:

  // string orderType = 14;
  void clear_ordertype();
  const std::string& ordertype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ordertype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ordertype();
  PROTOBUF_NODISCARD std::string* release_ordertype();
  void set_allocated_ordertype(std::string* ordertype);
  private:
  const std::string& _internal_ordertype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ordertype(const std::string& value);
  std::string* _internal_mutable_ordertype();
  public:

  // string status = 24;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string replaceStatus = 25;
  void clear_replacestatus();
  const std::string& replacestatus() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_replacestatus(ArgT0&& arg0, ArgT... args);
  std::string* mutable_replacestatus();
  PROTOBUF_NODISCARD std::string* release_replacestatus();
  void set_allocated_replacestatus(std::string* replacestatus);
  private:
  const std::string& _internal_replacestatus() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_replacestatus(const std::string& value);
  std::string* _internal_mutable_replacestatus();
  public:

  // string cancelStatus = 26;
  void clear_cancelstatus();
  const std::string& cancelstatus() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cancelstatus(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cancelstatus();
  PROTOBUF_NODISCARD std::string* release_cancelstatus();
  void set_allocated_cancelstatus(std::string* cancelstatus);
  private:
  const std::string& _internal_cancelstatus() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cancelstatus(const std::string& value);
  std::string* _internal_mutable_cancelstatus();
  public:

  // string name = 31;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string source = 32;
  void clear_source();
  const std::string& source() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source();
  PROTOBUF_NODISCARD std::string* release_source();
  void set_allocated_source(std::string* source);
  private:
  const std::string& _internal_source() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source(const std::string& value);
  std::string* _internal_mutable_source();
  public:

  // string errorMsg = 33;
  void clear_errormsg();
  const std::string& errormsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errormsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errormsg();
  PROTOBUF_NODISCARD std::string* release_errormsg();
  void set_allocated_errormsg(std::string* errormsg);
  private:
  const std::string& _internal_errormsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errormsg(const std::string& value);
  std::string* _internal_mutable_errormsg();
  public:

  // string attrDesc = 34;
  void clear_attrdesc();
  const std::string& attrdesc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_attrdesc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_attrdesc();
  PROTOBUF_NODISCARD std::string* release_attrdesc();
  void set_allocated_attrdesc(std::string* attrdesc);
  private:
  const std::string& _internal_attrdesc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_attrdesc(const std::string& value);
  std::string* _internal_mutable_attrdesc();
  public:

  // string userMark = 38;
  void clear_usermark();
  const std::string& usermark() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_usermark(ArgT0&& arg0, ArgT... args);
  std::string* mutable_usermark();
  PROTOBUF_NODISCARD std::string* release_usermark();
  void set_allocated_usermark(std::string* usermark);
  private:
  const std::string& _internal_usermark() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_usermark(const std::string& value);
  std::string* _internal_mutable_usermark();
  public:

  // sint64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // uint32 multiplier = 8;
  void clear_multiplier();
  uint32_t multiplier() const;
  void set_multiplier(uint32_t value);
  private:
  uint32_t _internal_multiplier() const;
  void _internal_set_multiplier(uint32_t value);
  public:

  // sint32 totalQuantityScale = 17;
  void clear_totalquantityscale();
  int32_t totalquantityscale() const;
  void set_totalquantityscale(int32_t value);
  private:
  int32_t _internal_totalquantityscale() const;
  void _internal_set_totalquantityscale(int32_t value);
  public:

  // sint64 totalQuantity = 16;
  void clear_totalquantity();
  int64_t totalquantity() const;
  void set_totalquantity(int64_t value);
  private:
  int64_t _internal_totalquantity() const;
  void _internal_set_totalquantity(int64_t value);
  public:

  // sint64 filledQuantity = 18;
  void clear_filledquantity();
  int64_t filledquantity() const;
  void set_filledquantity(int64_t value);
  private:
  int64_t _internal_filledquantity() const;
  void _internal_set_filledquantity(int64_t value);
  public:

  // double avgFillPrice = 20;
  void clear_avgfillprice();
  double avgfillprice() const;
  void set_avgfillprice(double value);
  private:
  double _internal_avgfillprice() const;
  void _internal_set_avgfillprice(double value);
  public:

  // double limitPrice = 21;
  void clear_limitprice();
  double limitprice() const;
  void set_limitprice(double value);
  private:
  double _internal_limitprice() const;
  void _internal_set_limitprice(double value);
  public:

  // double stopPrice = 22;
  void clear_stopprice();
  double stopprice() const;
  void set_stopprice(double value);
  private:
  double _internal_stopprice() const;
  void _internal_set_stopprice(double value);
  public:

  // double realizedPnl = 23;
  void clear_realizedpnl();
  double realizedpnl() const;
  void set_realizedpnl(double value);
  private:
  double _internal_realizedpnl() const;
  void _internal_set_realizedpnl(double value);
  public:

  // sint32 filledQuantityScale = 19;
  void clear_filledquantityscale();
  int32_t filledquantityscale() const;
  void set_filledquantityscale(int32_t value);
  private:
  int32_t _internal_filledquantityscale() const;
  void _internal_set_filledquantityscale(int32_t value);
  public:

  // bool isLong = 15;
  void clear_islong();
  bool islong() const;
  void set_islong(bool value);
  private:
  bool _internal_islong() const;
  void _internal_set_islong(bool value);
  public:

  // bool outsideRth = 27;
  void clear_outsiderth();
  bool outsiderth() const;
  void set_outsiderth(bool value);
  private:
  bool _internal_outsiderth() const;
  void _internal_set_outsiderth(bool value);
  public:

  // bool canModify = 28;
  void clear_canmodify();
  bool canmodify() const;
  void set_canmodify(bool value);
  private:
  bool _internal_canmodify() const;
  void _internal_set_canmodify(bool value);
  public:

  // bool canCancel = 29;
  void clear_cancancel();
  bool cancancel() const;
  void set_cancancel(bool value);
  private:
  bool _internal_cancancel() const;
  void _internal_set_cancancel(bool value);
  public:

  // bool liquidation = 30;
  void clear_liquidation();
  bool liquidation() const;
  void set_liquidation(bool value);
  private:
  bool _internal_liquidation() const;
  void _internal_set_liquidation(bool value);
  public:

  // float commissionAndFee = 35;
  void clear_commissionandfee();
  float commissionandfee() const;
  void set_commissionandfee(float value);
  private:
  float _internal_commissionandfee() const;
  void _internal_set_commissionandfee(float value);
  public:

  // uint64 openTime = 36;
  void clear_opentime();
  uint64_t opentime() const;
  void set_opentime(uint64_t value);
  private:
  uint64_t _internal_opentime() const;
  void _internal_set_opentime(uint64_t value);
  public:

  // uint64 timestamp = 37;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // double totalCashAmount = 39;
  void clear_totalcashamount();
  double totalcashamount() const;
  void set_totalcashamount(double value);
  private:
  double _internal_totalcashamount() const;
  void _internal_set_totalcashamount(double value);
  public:

  // double filledCashAmount = 40;
  void clear_filledcashamount();
  double filledcashamount() const;
  void set_filledcashamount(double value);
  private:
  double _internal_filledcashamount() const;
  void _internal_set_filledcashamount(double value);
  public:

  // double gst = 41;
  void clear_gst();
  double gst() const;
  void set_gst(double value);
  private:
  double _internal_gst() const;
  void _internal_set_gst(double value);
  public:

  // @@protoc_insertion_point(class_scope:tigeropen.push.pb.OrderStatusData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> attrlist_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbol_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr expiry_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr strike_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr right_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr identifier_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr action_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr market_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr currency_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr segtype_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sectype_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ordertype_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr replacestatus_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cancelstatus_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errormsg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr attrdesc_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr usermark_;
    int64_t id_;
    uint32_t multiplier_;
    int32_t totalquantityscale_;
    int64_t totalquantity_;
    int64_t filledquantity_;
    double avgfillprice_;
    double limitprice_;
    double stopprice_;
    double realizedpnl_;
    int32_t filledquantityscale_;
    bool islong_;
    bool outsiderth_;
    bool canmodify_;
    bool cancancel_;
    bool liquidation_;
    float commissionandfee_;
    uint64_t opentime_;
    uint64_t timestamp_;
    double totalcashamount_;
    double filledcashamount_;
    double gst_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_OrderStatusData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OrderStatusData

// sint64 id = 1;
inline void OrderStatusData::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t OrderStatusData::_internal_id() const {
  return _impl_.id_;
}
inline int64_t OrderStatusData::id() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.id)
  return _internal_id();
}
inline void OrderStatusData::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void OrderStatusData::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.id)
}

// string account = 2;
inline void OrderStatusData::clear_account() {
  _impl_.account_.ClearToEmpty();
}
inline const std::string& OrderStatusData::account() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.account)
  return _internal_account();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_account(ArgT0&& arg0, ArgT... args) {
 
 _impl_.account_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.account)
}
inline std::string* OrderStatusData::mutable_account() {
  std::string* _s = _internal_mutable_account();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.account)
  return _s;
}
inline const std::string& OrderStatusData::_internal_account() const {
  return _impl_.account_.Get();
}
inline void OrderStatusData::_internal_set_account(const std::string& value) {
  
  _impl_.account_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_account() {
  
  return _impl_.account_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_account() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.account)
  return _impl_.account_.Release();
}
inline void OrderStatusData::set_allocated_account(std::string* account) {
  if (account != nullptr) {
    
  } else {
    
  }
  _impl_.account_.SetAllocated(account, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.account_.IsDefault()) {
    _impl_.account_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.account)
}

// string symbol = 3;
inline void OrderStatusData::clear_symbol() {
  _impl_.symbol_.ClearToEmpty();
}
inline const std::string& OrderStatusData::symbol() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.symbol)
  return _internal_symbol();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_symbol(ArgT0&& arg0, ArgT... args) {
 
 _impl_.symbol_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.symbol)
}
inline std::string* OrderStatusData::mutable_symbol() {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.symbol)
  return _s;
}
inline const std::string& OrderStatusData::_internal_symbol() const {
  return _impl_.symbol_.Get();
}
inline void OrderStatusData::_internal_set_symbol(const std::string& value) {
  
  _impl_.symbol_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_symbol() {
  
  return _impl_.symbol_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_symbol() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.symbol)
  return _impl_.symbol_.Release();
}
inline void OrderStatusData::set_allocated_symbol(std::string* symbol) {
  if (symbol != nullptr) {
    
  } else {
    
  }
  _impl_.symbol_.SetAllocated(symbol, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.symbol_.IsDefault()) {
    _impl_.symbol_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.symbol)
}

// string expiry = 4;
inline void OrderStatusData::clear_expiry() {
  _impl_.expiry_.ClearToEmpty();
}
inline const std::string& OrderStatusData::expiry() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.expiry)
  return _internal_expiry();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_expiry(ArgT0&& arg0, ArgT... args) {
 
 _impl_.expiry_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.expiry)
}
inline std::string* OrderStatusData::mutable_expiry() {
  std::string* _s = _internal_mutable_expiry();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.expiry)
  return _s;
}
inline const std::string& OrderStatusData::_internal_expiry() const {
  return _impl_.expiry_.Get();
}
inline void OrderStatusData::_internal_set_expiry(const std::string& value) {
  
  _impl_.expiry_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_expiry() {
  
  return _impl_.expiry_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_expiry() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.expiry)
  return _impl_.expiry_.Release();
}
inline void OrderStatusData::set_allocated_expiry(std::string* expiry) {
  if (expiry != nullptr) {
    
  } else {
    
  }
  _impl_.expiry_.SetAllocated(expiry, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.expiry_.IsDefault()) {
    _impl_.expiry_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.expiry)
}

// string strike = 5;
inline void OrderStatusData::clear_strike() {
  _impl_.strike_.ClearToEmpty();
}
inline const std::string& OrderStatusData::strike() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.strike)
  return _internal_strike();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_strike(ArgT0&& arg0, ArgT... args) {
 
 _impl_.strike_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.strike)
}
inline std::string* OrderStatusData::mutable_strike() {
  std::string* _s = _internal_mutable_strike();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.strike)
  return _s;
}
inline const std::string& OrderStatusData::_internal_strike() const {
  return _impl_.strike_.Get();
}
inline void OrderStatusData::_internal_set_strike(const std::string& value) {
  
  _impl_.strike_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_strike() {
  
  return _impl_.strike_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_strike() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.strike)
  return _impl_.strike_.Release();
}
inline void OrderStatusData::set_allocated_strike(std::string* strike) {
  if (strike != nullptr) {
    
  } else {
    
  }
  _impl_.strike_.SetAllocated(strike, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.strike_.IsDefault()) {
    _impl_.strike_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.strike)
}

// string right = 6;
inline void OrderStatusData::clear_right() {
  _impl_.right_.ClearToEmpty();
}
inline const std::string& OrderStatusData::right() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.right)
  return _internal_right();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_right(ArgT0&& arg0, ArgT... args) {
 
 _impl_.right_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.right)
}
inline std::string* OrderStatusData::mutable_right() {
  std::string* _s = _internal_mutable_right();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.right)
  return _s;
}
inline const std::string& OrderStatusData::_internal_right() const {
  return _impl_.right_.Get();
}
inline void OrderStatusData::_internal_set_right(const std::string& value) {
  
  _impl_.right_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_right() {
  
  return _impl_.right_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_right() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.right)
  return _impl_.right_.Release();
}
inline void OrderStatusData::set_allocated_right(std::string* right) {
  if (right != nullptr) {
    
  } else {
    
  }
  _impl_.right_.SetAllocated(right, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.right_.IsDefault()) {
    _impl_.right_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.right)
}

// string identifier = 7;
inline void OrderStatusData::clear_identifier() {
  _impl_.identifier_.ClearToEmpty();
}
inline const std::string& OrderStatusData::identifier() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.identifier)
  return _internal_identifier();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_identifier(ArgT0&& arg0, ArgT... args) {
 
 _impl_.identifier_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.identifier)
}
inline std::string* OrderStatusData::mutable_identifier() {
  std::string* _s = _internal_mutable_identifier();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.identifier)
  return _s;
}
inline const std::string& OrderStatusData::_internal_identifier() const {
  return _impl_.identifier_.Get();
}
inline void OrderStatusData::_internal_set_identifier(const std::string& value) {
  
  _impl_.identifier_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_identifier() {
  
  return _impl_.identifier_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_identifier() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.identifier)
  return _impl_.identifier_.Release();
}
inline void OrderStatusData::set_allocated_identifier(std::string* identifier) {
  if (identifier != nullptr) {
    
  } else {
    
  }
  _impl_.identifier_.SetAllocated(identifier, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.identifier_.IsDefault()) {
    _impl_.identifier_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.identifier)
}

// uint32 multiplier = 8;
inline void OrderStatusData::clear_multiplier() {
  _impl_.multiplier_ = 0u;
}
inline uint32_t OrderStatusData::_internal_multiplier() const {
  return _impl_.multiplier_;
}
inline uint32_t OrderStatusData::multiplier() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.multiplier)
  return _internal_multiplier();
}
inline void OrderStatusData::_internal_set_multiplier(uint32_t value) {
  
  _impl_.multiplier_ = value;
}
inline void OrderStatusData::set_multiplier(uint32_t value) {
  _internal_set_multiplier(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.multiplier)
}

// string action = 9;
inline void OrderStatusData::clear_action() {
  _impl_.action_.ClearToEmpty();
}
inline const std::string& OrderStatusData::action() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.action)
  return _internal_action();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_action(ArgT0&& arg0, ArgT... args) {
 
 _impl_.action_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.action)
}
inline std::string* OrderStatusData::mutable_action() {
  std::string* _s = _internal_mutable_action();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.action)
  return _s;
}
inline const std::string& OrderStatusData::_internal_action() const {
  return _impl_.action_.Get();
}
inline void OrderStatusData::_internal_set_action(const std::string& value) {
  
  _impl_.action_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_action() {
  
  return _impl_.action_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_action() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.action)
  return _impl_.action_.Release();
}
inline void OrderStatusData::set_allocated_action(std::string* action) {
  if (action != nullptr) {
    
  } else {
    
  }
  _impl_.action_.SetAllocated(action, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.action_.IsDefault()) {
    _impl_.action_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.action)
}

// string market = 10;
inline void OrderStatusData::clear_market() {
  _impl_.market_.ClearToEmpty();
}
inline const std::string& OrderStatusData::market() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.market)
  return _internal_market();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_market(ArgT0&& arg0, ArgT... args) {
 
 _impl_.market_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.market)
}
inline std::string* OrderStatusData::mutable_market() {
  std::string* _s = _internal_mutable_market();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.market)
  return _s;
}
inline const std::string& OrderStatusData::_internal_market() const {
  return _impl_.market_.Get();
}
inline void OrderStatusData::_internal_set_market(const std::string& value) {
  
  _impl_.market_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_market() {
  
  return _impl_.market_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_market() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.market)
  return _impl_.market_.Release();
}
inline void OrderStatusData::set_allocated_market(std::string* market) {
  if (market != nullptr) {
    
  } else {
    
  }
  _impl_.market_.SetAllocated(market, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.market_.IsDefault()) {
    _impl_.market_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.market)
}

// string currency = 11;
inline void OrderStatusData::clear_currency() {
  _impl_.currency_.ClearToEmpty();
}
inline const std::string& OrderStatusData::currency() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.currency)
  return _internal_currency();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_currency(ArgT0&& arg0, ArgT... args) {
 
 _impl_.currency_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.currency)
}
inline std::string* OrderStatusData::mutable_currency() {
  std::string* _s = _internal_mutable_currency();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.currency)
  return _s;
}
inline const std::string& OrderStatusData::_internal_currency() const {
  return _impl_.currency_.Get();
}
inline void OrderStatusData::_internal_set_currency(const std::string& value) {
  
  _impl_.currency_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_currency() {
  
  return _impl_.currency_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_currency() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.currency)
  return _impl_.currency_.Release();
}
inline void OrderStatusData::set_allocated_currency(std::string* currency) {
  if (currency != nullptr) {
    
  } else {
    
  }
  _impl_.currency_.SetAllocated(currency, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.currency_.IsDefault()) {
    _impl_.currency_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.currency)
}

// string segType = 12;
inline void OrderStatusData::clear_segtype() {
  _impl_.segtype_.ClearToEmpty();
}
inline const std::string& OrderStatusData::segtype() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.segType)
  return _internal_segtype();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_segtype(ArgT0&& arg0, ArgT... args) {
 
 _impl_.segtype_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.segType)
}
inline std::string* OrderStatusData::mutable_segtype() {
  std::string* _s = _internal_mutable_segtype();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.segType)
  return _s;
}
inline const std::string& OrderStatusData::_internal_segtype() const {
  return _impl_.segtype_.Get();
}
inline void OrderStatusData::_internal_set_segtype(const std::string& value) {
  
  _impl_.segtype_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_segtype() {
  
  return _impl_.segtype_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_segtype() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.segType)
  return _impl_.segtype_.Release();
}
inline void OrderStatusData::set_allocated_segtype(std::string* segtype) {
  if (segtype != nullptr) {
    
  } else {
    
  }
  _impl_.segtype_.SetAllocated(segtype, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.segtype_.IsDefault()) {
    _impl_.segtype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.segType)
}

// string secType = 13;
inline void OrderStatusData::clear_sectype() {
  _impl_.sectype_.ClearToEmpty();
}
inline const std::string& OrderStatusData::sectype() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.secType)
  return _internal_sectype();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_sectype(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sectype_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.secType)
}
inline std::string* OrderStatusData::mutable_sectype() {
  std::string* _s = _internal_mutable_sectype();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.secType)
  return _s;
}
inline const std::string& OrderStatusData::_internal_sectype() const {
  return _impl_.sectype_.Get();
}
inline void OrderStatusData::_internal_set_sectype(const std::string& value) {
  
  _impl_.sectype_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_sectype() {
  
  return _impl_.sectype_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_sectype() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.secType)
  return _impl_.sectype_.Release();
}
inline void OrderStatusData::set_allocated_sectype(std::string* sectype) {
  if (sectype != nullptr) {
    
  } else {
    
  }
  _impl_.sectype_.SetAllocated(sectype, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sectype_.IsDefault()) {
    _impl_.sectype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.secType)
}

// string orderType = 14;
inline void OrderStatusData::clear_ordertype() {
  _impl_.ordertype_.ClearToEmpty();
}
inline const std::string& OrderStatusData::ordertype() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.orderType)
  return _internal_ordertype();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_ordertype(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ordertype_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.orderType)
}
inline std::string* OrderStatusData::mutable_ordertype() {
  std::string* _s = _internal_mutable_ordertype();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.orderType)
  return _s;
}
inline const std::string& OrderStatusData::_internal_ordertype() const {
  return _impl_.ordertype_.Get();
}
inline void OrderStatusData::_internal_set_ordertype(const std::string& value) {
  
  _impl_.ordertype_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_ordertype() {
  
  return _impl_.ordertype_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_ordertype() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.orderType)
  return _impl_.ordertype_.Release();
}
inline void OrderStatusData::set_allocated_ordertype(std::string* ordertype) {
  if (ordertype != nullptr) {
    
  } else {
    
  }
  _impl_.ordertype_.SetAllocated(ordertype, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ordertype_.IsDefault()) {
    _impl_.ordertype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.orderType)
}

// bool isLong = 15;
inline void OrderStatusData::clear_islong() {
  _impl_.islong_ = false;
}
inline bool OrderStatusData::_internal_islong() const {
  return _impl_.islong_;
}
inline bool OrderStatusData::islong() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.isLong)
  return _internal_islong();
}
inline void OrderStatusData::_internal_set_islong(bool value) {
  
  _impl_.islong_ = value;
}
inline void OrderStatusData::set_islong(bool value) {
  _internal_set_islong(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.isLong)
}

// sint64 totalQuantity = 16;
inline void OrderStatusData::clear_totalquantity() {
  _impl_.totalquantity_ = int64_t{0};
}
inline int64_t OrderStatusData::_internal_totalquantity() const {
  return _impl_.totalquantity_;
}
inline int64_t OrderStatusData::totalquantity() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.totalQuantity)
  return _internal_totalquantity();
}
inline void OrderStatusData::_internal_set_totalquantity(int64_t value) {
  
  _impl_.totalquantity_ = value;
}
inline void OrderStatusData::set_totalquantity(int64_t value) {
  _internal_set_totalquantity(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.totalQuantity)
}

// sint32 totalQuantityScale = 17;
inline void OrderStatusData::clear_totalquantityscale() {
  _impl_.totalquantityscale_ = 0;
}
inline int32_t OrderStatusData::_internal_totalquantityscale() const {
  return _impl_.totalquantityscale_;
}
inline int32_t OrderStatusData::totalquantityscale() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.totalQuantityScale)
  return _internal_totalquantityscale();
}
inline void OrderStatusData::_internal_set_totalquantityscale(int32_t value) {
  
  _impl_.totalquantityscale_ = value;
}
inline void OrderStatusData::set_totalquantityscale(int32_t value) {
  _internal_set_totalquantityscale(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.totalQuantityScale)
}

// sint64 filledQuantity = 18;
inline void OrderStatusData::clear_filledquantity() {
  _impl_.filledquantity_ = int64_t{0};
}
inline int64_t OrderStatusData::_internal_filledquantity() const {
  return _impl_.filledquantity_;
}
inline int64_t OrderStatusData::filledquantity() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.filledQuantity)
  return _internal_filledquantity();
}
inline void OrderStatusData::_internal_set_filledquantity(int64_t value) {
  
  _impl_.filledquantity_ = value;
}
inline void OrderStatusData::set_filledquantity(int64_t value) {
  _internal_set_filledquantity(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.filledQuantity)
}

// sint32 filledQuantityScale = 19;
inline void OrderStatusData::clear_filledquantityscale() {
  _impl_.filledquantityscale_ = 0;
}
inline int32_t OrderStatusData::_internal_filledquantityscale() const {
  return _impl_.filledquantityscale_;
}
inline int32_t OrderStatusData::filledquantityscale() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.filledQuantityScale)
  return _internal_filledquantityscale();
}
inline void OrderStatusData::_internal_set_filledquantityscale(int32_t value) {
  
  _impl_.filledquantityscale_ = value;
}
inline void OrderStatusData::set_filledquantityscale(int32_t value) {
  _internal_set_filledquantityscale(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.filledQuantityScale)
}

// double avgFillPrice = 20;
inline void OrderStatusData::clear_avgfillprice() {
  _impl_.avgfillprice_ = 0;
}
inline double OrderStatusData::_internal_avgfillprice() const {
  return _impl_.avgfillprice_;
}
inline double OrderStatusData::avgfillprice() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.avgFillPrice)
  return _internal_avgfillprice();
}
inline void OrderStatusData::_internal_set_avgfillprice(double value) {
  
  _impl_.avgfillprice_ = value;
}
inline void OrderStatusData::set_avgfillprice(double value) {
  _internal_set_avgfillprice(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.avgFillPrice)
}

// double limitPrice = 21;
inline void OrderStatusData::clear_limitprice() {
  _impl_.limitprice_ = 0;
}
inline double OrderStatusData::_internal_limitprice() const {
  return _impl_.limitprice_;
}
inline double OrderStatusData::limitprice() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.limitPrice)
  return _internal_limitprice();
}
inline void OrderStatusData::_internal_set_limitprice(double value) {
  
  _impl_.limitprice_ = value;
}
inline void OrderStatusData::set_limitprice(double value) {
  _internal_set_limitprice(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.limitPrice)
}

// double stopPrice = 22;
inline void OrderStatusData::clear_stopprice() {
  _impl_.stopprice_ = 0;
}
inline double OrderStatusData::_internal_stopprice() const {
  return _impl_.stopprice_;
}
inline double OrderStatusData::stopprice() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.stopPrice)
  return _internal_stopprice();
}
inline void OrderStatusData::_internal_set_stopprice(double value) {
  
  _impl_.stopprice_ = value;
}
inline void OrderStatusData::set_stopprice(double value) {
  _internal_set_stopprice(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.stopPrice)
}

// double realizedPnl = 23;
inline void OrderStatusData::clear_realizedpnl() {
  _impl_.realizedpnl_ = 0;
}
inline double OrderStatusData::_internal_realizedpnl() const {
  return _impl_.realizedpnl_;
}
inline double OrderStatusData::realizedpnl() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.realizedPnl)
  return _internal_realizedpnl();
}
inline void OrderStatusData::_internal_set_realizedpnl(double value) {
  
  _impl_.realizedpnl_ = value;
}
inline void OrderStatusData::set_realizedpnl(double value) {
  _internal_set_realizedpnl(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.realizedPnl)
}

// string status = 24;
inline void OrderStatusData::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& OrderStatusData::status() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.status)
}
inline std::string* OrderStatusData::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.status)
  return _s;
}
inline const std::string& OrderStatusData::_internal_status() const {
  return _impl_.status_.Get();
}
inline void OrderStatusData::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_status() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.status)
  return _impl_.status_.Release();
}
inline void OrderStatusData::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.status)
}

// string replaceStatus = 25;
inline void OrderStatusData::clear_replacestatus() {
  _impl_.replacestatus_.ClearToEmpty();
}
inline const std::string& OrderStatusData::replacestatus() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.replaceStatus)
  return _internal_replacestatus();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_replacestatus(ArgT0&& arg0, ArgT... args) {
 
 _impl_.replacestatus_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.replaceStatus)
}
inline std::string* OrderStatusData::mutable_replacestatus() {
  std::string* _s = _internal_mutable_replacestatus();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.replaceStatus)
  return _s;
}
inline const std::string& OrderStatusData::_internal_replacestatus() const {
  return _impl_.replacestatus_.Get();
}
inline void OrderStatusData::_internal_set_replacestatus(const std::string& value) {
  
  _impl_.replacestatus_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_replacestatus() {
  
  return _impl_.replacestatus_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_replacestatus() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.replaceStatus)
  return _impl_.replacestatus_.Release();
}
inline void OrderStatusData::set_allocated_replacestatus(std::string* replacestatus) {
  if (replacestatus != nullptr) {
    
  } else {
    
  }
  _impl_.replacestatus_.SetAllocated(replacestatus, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.replacestatus_.IsDefault()) {
    _impl_.replacestatus_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.replaceStatus)
}

// string cancelStatus = 26;
inline void OrderStatusData::clear_cancelstatus() {
  _impl_.cancelstatus_.ClearToEmpty();
}
inline const std::string& OrderStatusData::cancelstatus() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.cancelStatus)
  return _internal_cancelstatus();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_cancelstatus(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cancelstatus_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.cancelStatus)
}
inline std::string* OrderStatusData::mutable_cancelstatus() {
  std::string* _s = _internal_mutable_cancelstatus();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.cancelStatus)
  return _s;
}
inline const std::string& OrderStatusData::_internal_cancelstatus() const {
  return _impl_.cancelstatus_.Get();
}
inline void OrderStatusData::_internal_set_cancelstatus(const std::string& value) {
  
  _impl_.cancelstatus_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_cancelstatus() {
  
  return _impl_.cancelstatus_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_cancelstatus() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.cancelStatus)
  return _impl_.cancelstatus_.Release();
}
inline void OrderStatusData::set_allocated_cancelstatus(std::string* cancelstatus) {
  if (cancelstatus != nullptr) {
    
  } else {
    
  }
  _impl_.cancelstatus_.SetAllocated(cancelstatus, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cancelstatus_.IsDefault()) {
    _impl_.cancelstatus_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.cancelStatus)
}

// bool outsideRth = 27;
inline void OrderStatusData::clear_outsiderth() {
  _impl_.outsiderth_ = false;
}
inline bool OrderStatusData::_internal_outsiderth() const {
  return _impl_.outsiderth_;
}
inline bool OrderStatusData::outsiderth() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.outsideRth)
  return _internal_outsiderth();
}
inline void OrderStatusData::_internal_set_outsiderth(bool value) {
  
  _impl_.outsiderth_ = value;
}
inline void OrderStatusData::set_outsiderth(bool value) {
  _internal_set_outsiderth(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.outsideRth)
}

// bool canModify = 28;
inline void OrderStatusData::clear_canmodify() {
  _impl_.canmodify_ = false;
}
inline bool OrderStatusData::_internal_canmodify() const {
  return _impl_.canmodify_;
}
inline bool OrderStatusData::canmodify() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.canModify)
  return _internal_canmodify();
}
inline void OrderStatusData::_internal_set_canmodify(bool value) {
  
  _impl_.canmodify_ = value;
}
inline void OrderStatusData::set_canmodify(bool value) {
  _internal_set_canmodify(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.canModify)
}

// bool canCancel = 29;
inline void OrderStatusData::clear_cancancel() {
  _impl_.cancancel_ = false;
}
inline bool OrderStatusData::_internal_cancancel() const {
  return _impl_.cancancel_;
}
inline bool OrderStatusData::cancancel() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.canCancel)
  return _internal_cancancel();
}
inline void OrderStatusData::_internal_set_cancancel(bool value) {
  
  _impl_.cancancel_ = value;
}
inline void OrderStatusData::set_cancancel(bool value) {
  _internal_set_cancancel(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.canCancel)
}

// bool liquidation = 30;
inline void OrderStatusData::clear_liquidation() {
  _impl_.liquidation_ = false;
}
inline bool OrderStatusData::_internal_liquidation() const {
  return _impl_.liquidation_;
}
inline bool OrderStatusData::liquidation() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.liquidation)
  return _internal_liquidation();
}
inline void OrderStatusData::_internal_set_liquidation(bool value) {
  
  _impl_.liquidation_ = value;
}
inline void OrderStatusData::set_liquidation(bool value) {
  _internal_set_liquidation(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.liquidation)
}

// string name = 31;
inline void OrderStatusData::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& OrderStatusData::name() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.name)
}
inline std::string* OrderStatusData::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.name)
  return _s;
}
inline const std::string& OrderStatusData::_internal_name() const {
  return _impl_.name_.Get();
}
inline void OrderStatusData::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_name() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.name)
  return _impl_.name_.Release();
}
inline void OrderStatusData::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.name)
}

// string source = 32;
inline void OrderStatusData::clear_source() {
  _impl_.source_.ClearToEmpty();
}
inline const std::string& OrderStatusData::source() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.source)
  return _internal_source();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_source(ArgT0&& arg0, ArgT... args) {
 
 _impl_.source_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.source)
}
inline std::string* OrderStatusData::mutable_source() {
  std::string* _s = _internal_mutable_source();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.source)
  return _s;
}
inline const std::string& OrderStatusData::_internal_source() const {
  return _impl_.source_.Get();
}
inline void OrderStatusData::_internal_set_source(const std::string& value) {
  
  _impl_.source_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_source() {
  
  return _impl_.source_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_source() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.source)
  return _impl_.source_.Release();
}
inline void OrderStatusData::set_allocated_source(std::string* source) {
  if (source != nullptr) {
    
  } else {
    
  }
  _impl_.source_.SetAllocated(source, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_.IsDefault()) {
    _impl_.source_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.source)
}

// string errorMsg = 33;
inline void OrderStatusData::clear_errormsg() {
  _impl_.errormsg_.ClearToEmpty();
}
inline const std::string& OrderStatusData::errormsg() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.errorMsg)
  return _internal_errormsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_errormsg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errormsg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.errorMsg)
}
inline std::string* OrderStatusData::mutable_errormsg() {
  std::string* _s = _internal_mutable_errormsg();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.errorMsg)
  return _s;
}
inline const std::string& OrderStatusData::_internal_errormsg() const {
  return _impl_.errormsg_.Get();
}
inline void OrderStatusData::_internal_set_errormsg(const std::string& value) {
  
  _impl_.errormsg_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_errormsg() {
  
  return _impl_.errormsg_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_errormsg() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.errorMsg)
  return _impl_.errormsg_.Release();
}
inline void OrderStatusData::set_allocated_errormsg(std::string* errormsg) {
  if (errormsg != nullptr) {
    
  } else {
    
  }
  _impl_.errormsg_.SetAllocated(errormsg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errormsg_.IsDefault()) {
    _impl_.errormsg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.errorMsg)
}

// string attrDesc = 34;
inline void OrderStatusData::clear_attrdesc() {
  _impl_.attrdesc_.ClearToEmpty();
}
inline const std::string& OrderStatusData::attrdesc() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.attrDesc)
  return _internal_attrdesc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_attrdesc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.attrdesc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.attrDesc)
}
inline std::string* OrderStatusData::mutable_attrdesc() {
  std::string* _s = _internal_mutable_attrdesc();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.attrDesc)
  return _s;
}
inline const std::string& OrderStatusData::_internal_attrdesc() const {
  return _impl_.attrdesc_.Get();
}
inline void OrderStatusData::_internal_set_attrdesc(const std::string& value) {
  
  _impl_.attrdesc_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_attrdesc() {
  
  return _impl_.attrdesc_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_attrdesc() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.attrDesc)
  return _impl_.attrdesc_.Release();
}
inline void OrderStatusData::set_allocated_attrdesc(std::string* attrdesc) {
  if (attrdesc != nullptr) {
    
  } else {
    
  }
  _impl_.attrdesc_.SetAllocated(attrdesc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.attrdesc_.IsDefault()) {
    _impl_.attrdesc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.attrDesc)
}

// float commissionAndFee = 35;
inline void OrderStatusData::clear_commissionandfee() {
  _impl_.commissionandfee_ = 0;
}
inline float OrderStatusData::_internal_commissionandfee() const {
  return _impl_.commissionandfee_;
}
inline float OrderStatusData::commissionandfee() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.commissionAndFee)
  return _internal_commissionandfee();
}
inline void OrderStatusData::_internal_set_commissionandfee(float value) {
  
  _impl_.commissionandfee_ = value;
}
inline void OrderStatusData::set_commissionandfee(float value) {
  _internal_set_commissionandfee(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.commissionAndFee)
}

// uint64 openTime = 36;
inline void OrderStatusData::clear_opentime() {
  _impl_.opentime_ = uint64_t{0u};
}
inline uint64_t OrderStatusData::_internal_opentime() const {
  return _impl_.opentime_;
}
inline uint64_t OrderStatusData::opentime() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.openTime)
  return _internal_opentime();
}
inline void OrderStatusData::_internal_set_opentime(uint64_t value) {
  
  _impl_.opentime_ = value;
}
inline void OrderStatusData::set_opentime(uint64_t value) {
  _internal_set_opentime(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.openTime)
}

// uint64 timestamp = 37;
inline void OrderStatusData::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t OrderStatusData::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t OrderStatusData::timestamp() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.timestamp)
  return _internal_timestamp();
}
inline void OrderStatusData::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void OrderStatusData::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.timestamp)
}

// string userMark = 38;
inline void OrderStatusData::clear_usermark() {
  _impl_.usermark_.ClearToEmpty();
}
inline const std::string& OrderStatusData::usermark() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.userMark)
  return _internal_usermark();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OrderStatusData::set_usermark(ArgT0&& arg0, ArgT... args) {
 
 _impl_.usermark_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.userMark)
}
inline std::string* OrderStatusData::mutable_usermark() {
  std::string* _s = _internal_mutable_usermark();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.userMark)
  return _s;
}
inline const std::string& OrderStatusData::_internal_usermark() const {
  return _impl_.usermark_.Get();
}
inline void OrderStatusData::_internal_set_usermark(const std::string& value) {
  
  _impl_.usermark_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderStatusData::_internal_mutable_usermark() {
  
  return _impl_.usermark_.Mutable(GetArenaForAllocation());
}
inline std::string* OrderStatusData::release_usermark() {
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.OrderStatusData.userMark)
  return _impl_.usermark_.Release();
}
inline void OrderStatusData::set_allocated_usermark(std::string* usermark) {
  if (usermark != nullptr) {
    
  } else {
    
  }
  _impl_.usermark_.SetAllocated(usermark, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.usermark_.IsDefault()) {
    _impl_.usermark_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.OrderStatusData.userMark)
}

// double totalCashAmount = 39;
inline void OrderStatusData::clear_totalcashamount() {
  _impl_.totalcashamount_ = 0;
}
inline double OrderStatusData::_internal_totalcashamount() const {
  return _impl_.totalcashamount_;
}
inline double OrderStatusData::totalcashamount() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.totalCashAmount)
  return _internal_totalcashamount();
}
inline void OrderStatusData::_internal_set_totalcashamount(double value) {
  
  _impl_.totalcashamount_ = value;
}
inline void OrderStatusData::set_totalcashamount(double value) {
  _internal_set_totalcashamount(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.totalCashAmount)
}

// double filledCashAmount = 40;
inline void OrderStatusData::clear_filledcashamount() {
  _impl_.filledcashamount_ = 0;
}
inline double OrderStatusData::_internal_filledcashamount() const {
  return _impl_.filledcashamount_;
}
inline double OrderStatusData::filledcashamount() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.filledCashAmount)
  return _internal_filledcashamount();
}
inline void OrderStatusData::_internal_set_filledcashamount(double value) {
  
  _impl_.filledcashamount_ = value;
}
inline void OrderStatusData::set_filledcashamount(double value) {
  _internal_set_filledcashamount(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.filledCashAmount)
}

// double gst = 41;
inline void OrderStatusData::clear_gst() {
  _impl_.gst_ = 0;
}
inline double OrderStatusData::_internal_gst() const {
  return _impl_.gst_;
}
inline double OrderStatusData::gst() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.gst)
  return _internal_gst();
}
inline void OrderStatusData::_internal_set_gst(double value) {
  
  _impl_.gst_ = value;
}
inline void OrderStatusData::set_gst(double value) {
  _internal_set_gst(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.gst)
}

// repeated string attrList = 42;
inline int OrderStatusData::_internal_attrlist_size() const {
  return _impl_.attrlist_.size();
}
inline int OrderStatusData::attrlist_size() const {
  return _internal_attrlist_size();
}
inline void OrderStatusData::clear_attrlist() {
  _impl_.attrlist_.Clear();
}
inline std::string* OrderStatusData::add_attrlist() {
  std::string* _s = _internal_add_attrlist();
  // @@protoc_insertion_point(field_add_mutable:tigeropen.push.pb.OrderStatusData.attrList)
  return _s;
}
inline const std::string& OrderStatusData::_internal_attrlist(int index) const {
  return _impl_.attrlist_.Get(index);
}
inline const std::string& OrderStatusData::attrlist(int index) const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.OrderStatusData.attrList)
  return _internal_attrlist(index);
}
inline std::string* OrderStatusData::mutable_attrlist(int index) {
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.OrderStatusData.attrList)
  return _impl_.attrlist_.Mutable(index);
}
inline void OrderStatusData::set_attrlist(int index, const std::string& value) {
  _impl_.attrlist_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.attrList)
}
inline void OrderStatusData::set_attrlist(int index, std::string&& value) {
  _impl_.attrlist_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.OrderStatusData.attrList)
}
inline void OrderStatusData::set_attrlist(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.attrlist_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tigeropen.push.pb.OrderStatusData.attrList)
}
inline void OrderStatusData::set_attrlist(int index, const char* value, size_t size) {
  _impl_.attrlist_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tigeropen.push.pb.OrderStatusData.attrList)
}
inline std::string* OrderStatusData::_internal_add_attrlist() {
  return _impl_.attrlist_.Add();
}
inline void OrderStatusData::add_attrlist(const std::string& value) {
  _impl_.attrlist_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tigeropen.push.pb.OrderStatusData.attrList)
}
inline void OrderStatusData::add_attrlist(std::string&& value) {
  _impl_.attrlist_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tigeropen.push.pb.OrderStatusData.attrList)
}
inline void OrderStatusData::add_attrlist(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.attrlist_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tigeropen.push.pb.OrderStatusData.attrList)
}
inline void OrderStatusData::add_attrlist(const char* value, size_t size) {
  _impl_.attrlist_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tigeropen.push.pb.OrderStatusData.attrList)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
OrderStatusData::attrlist() const {
  // @@protoc_insertion_point(field_list:tigeropen.push.pb.OrderStatusData.attrList)
  return _impl_.attrlist_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
OrderStatusData::mutable_attrlist() {
  // @@protoc_insertion_point(field_mutable_list:tigeropen.push.pb.OrderStatusData.attrList)
  return &_impl_.attrlist_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace push
}  // namespace tigeropen

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_OrderStatusData_2eproto
