// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

#include "Request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace tigeropen {
namespace push {
namespace pb {
PROTOBUF_CONSTEXPR Request_Connect::Request_Connect(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.tigerid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sign_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sdkversion_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.acceptversion_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sendinterval_)*/0u
  , /*decltype(_impl_.receiveinterval_)*/0u
  , /*decltype(_impl_.usefulltick_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Request_ConnectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Request_ConnectDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Request_ConnectDefaultTypeInternal() {}
  union {
    Request_Connect _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Request_ConnectDefaultTypeInternal _Request_Connect_default_instance_;
PROTOBUF_CONSTEXPR Request_Subscribe::Request_Subscribe(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.symbols_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.account_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.market_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.datatype_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Request_SubscribeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Request_SubscribeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Request_SubscribeDefaultTypeInternal() {}
  union {
    Request_Subscribe _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Request_SubscribeDefaultTypeInternal _Request_Subscribe_default_instance_;
PROTOBUF_CONSTEXPR Request::Request(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.subscribe_)*/nullptr
  , /*decltype(_impl_.connect_)*/nullptr
  , /*decltype(_impl_.command_)*/0
  , /*decltype(_impl_.id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestDefaultTypeInternal() {}
  union {
    Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestDefaultTypeInternal _Request_default_instance_;
}  // namespace pb
}  // namespace push
}  // namespace tigeropen
static ::_pb::Metadata file_level_metadata_Request_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Request_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Request_2eproto = nullptr;

const uint32_t TableStruct_Request_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Connect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Connect, _impl_.tigerid_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Connect, _impl_.sign_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Connect, _impl_.sdkversion_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Connect, _impl_.acceptversion_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Connect, _impl_.sendinterval_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Connect, _impl_.receiveinterval_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Connect, _impl_.usefulltick_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Subscribe, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Subscribe, _impl_.datatype_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Subscribe, _impl_.symbols_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Subscribe, _impl_.account_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request_Subscribe, _impl_.market_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request, _impl_.command_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request, _impl_.subscribe_),
  PROTOBUF_FIELD_OFFSET(::tigeropen::push::pb::Request, _impl_.connect_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::tigeropen::push::pb::Request_Connect)},
  { 13, -1, -1, sizeof(::tigeropen::push::pb::Request_Subscribe)},
  { 23, -1, -1, sizeof(::tigeropen::push::pb::Request)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::tigeropen::push::pb::_Request_Connect_default_instance_._instance,
  &::tigeropen::push::pb::_Request_Subscribe_default_instance_._instance,
  &::tigeropen::push::pb::_Request_default_instance_._instance,
};

const char descriptor_table_protodef_Request_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rRequest.proto\022\021tigeropen.push.pb\032\022Sock"
  "etCommon.proto\"\322\003\n\007Request\0228\n\007command\030\001 "
  "\001(\0162\'.tigeropen.push.pb.SocketCommon.Com"
  "mand\022\n\n\002id\030\002 \001(\r\0227\n\tsubscribe\030\003 \001(\0132$.ti"
  "geropen.push.pb.Request.Subscribe\0223\n\007con"
  "nect\030\004 \001(\0132\".tigeropen.push.pb.Request.C"
  "onnect\032\227\001\n\007Connect\022\017\n\007tigerId\030\001 \001(\t\022\014\n\004s"
  "ign\030\002 \001(\t\022\022\n\nsdkVersion\030\003 \001(\t\022\025\n\racceptV"
  "ersion\030\004 \001(\t\022\024\n\014sendInterval\030\005 \001(\r\022\027\n\017re"
  "ceiveInterval\030\006 \001(\r\022\023\n\013useFullTick\030\007 \001(\010"
  "\032y\n\tSubscribe\022:\n\010dataType\030\001 \001(\0162(.tigero"
  "pen.push.pb.SocketCommon.DataType\022\017\n\007sym"
  "bols\030\002 \001(\t\022\017\n\007account\030\003 \001(\t\022\016\n\006market\030\004 "
  "\001(\tP\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Request_2eproto_deps[1] = {
  &::descriptor_table_SocketCommon_2eproto,
};
static ::_pbi::once_flag descriptor_table_Request_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Request_2eproto = {
    false, false, 533, descriptor_table_protodef_Request_2eproto,
    "Request.proto",
    &descriptor_table_Request_2eproto_once, descriptor_table_Request_2eproto_deps, 1, 3,
    schemas, file_default_instances, TableStruct_Request_2eproto::offsets,
    file_level_metadata_Request_2eproto, file_level_enum_descriptors_Request_2eproto,
    file_level_service_descriptors_Request_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Request_2eproto_getter() {
  return &descriptor_table_Request_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Request_2eproto(&descriptor_table_Request_2eproto);
namespace tigeropen {
namespace push {
namespace pb {

// ===================================================================

class Request_Connect::_Internal {
 public:
};

Request_Connect::Request_Connect(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tigeropen.push.pb.Request.Connect)
}
Request_Connect::Request_Connect(const Request_Connect& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Request_Connect* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.tigerid_){}
    , decltype(_impl_.sign_){}
    , decltype(_impl_.sdkversion_){}
    , decltype(_impl_.acceptversion_){}
    , decltype(_impl_.sendinterval_){}
    , decltype(_impl_.receiveinterval_){}
    , decltype(_impl_.usefulltick_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.tigerid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tigerid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_tigerid().empty()) {
    _this->_impl_.tigerid_.Set(from._internal_tigerid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sign_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sign_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sign().empty()) {
    _this->_impl_.sign_.Set(from._internal_sign(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sdkversion_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sdkversion_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sdkversion().empty()) {
    _this->_impl_.sdkversion_.Set(from._internal_sdkversion(), 
      _this->GetArenaForAllocation());
  }
  _impl_.acceptversion_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.acceptversion_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_acceptversion().empty()) {
    _this->_impl_.acceptversion_.Set(from._internal_acceptversion(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.sendinterval_, &from._impl_.sendinterval_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.usefulltick_) -
    reinterpret_cast<char*>(&_impl_.sendinterval_)) + sizeof(_impl_.usefulltick_));
  // @@protoc_insertion_point(copy_constructor:tigeropen.push.pb.Request.Connect)
}

inline void Request_Connect::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.tigerid_){}
    , decltype(_impl_.sign_){}
    , decltype(_impl_.sdkversion_){}
    , decltype(_impl_.acceptversion_){}
    , decltype(_impl_.sendinterval_){0u}
    , decltype(_impl_.receiveinterval_){0u}
    , decltype(_impl_.usefulltick_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.tigerid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tigerid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sign_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sign_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sdkversion_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sdkversion_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.acceptversion_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.acceptversion_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Request_Connect::~Request_Connect() {
  // @@protoc_insertion_point(destructor:tigeropen.push.pb.Request.Connect)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Request_Connect::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.tigerid_.Destroy();
  _impl_.sign_.Destroy();
  _impl_.sdkversion_.Destroy();
  _impl_.acceptversion_.Destroy();
}

void Request_Connect::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Request_Connect::Clear() {
// @@protoc_insertion_point(message_clear_start:tigeropen.push.pb.Request.Connect)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tigerid_.ClearToEmpty();
  _impl_.sign_.ClearToEmpty();
  _impl_.sdkversion_.ClearToEmpty();
  _impl_.acceptversion_.ClearToEmpty();
  ::memset(&_impl_.sendinterval_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.usefulltick_) -
      reinterpret_cast<char*>(&_impl_.sendinterval_)) + sizeof(_impl_.usefulltick_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Request_Connect::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string tigerId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_tigerid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tigeropen.push.pb.Request.Connect.tigerId"));
        } else
          goto handle_unusual;
        continue;
      // string sign = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_sign();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tigeropen.push.pb.Request.Connect.sign"));
        } else
          goto handle_unusual;
        continue;
      // string sdkVersion = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_sdkversion();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tigeropen.push.pb.Request.Connect.sdkVersion"));
        } else
          goto handle_unusual;
        continue;
      // string acceptVersion = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_acceptversion();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tigeropen.push.pb.Request.Connect.acceptVersion"));
        } else
          goto handle_unusual;
        continue;
      // uint32 sendInterval = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.sendinterval_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 receiveInterval = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.receiveinterval_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool useFullTick = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.usefulltick_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Request_Connect::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tigeropen.push.pb.Request.Connect)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string tigerId = 1;
  if (!this->_internal_tigerid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_tigerid().data(), static_cast<int>(this->_internal_tigerid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tigeropen.push.pb.Request.Connect.tigerId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_tigerid(), target);
  }

  // string sign = 2;
  if (!this->_internal_sign().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sign().data(), static_cast<int>(this->_internal_sign().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tigeropen.push.pb.Request.Connect.sign");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sign(), target);
  }

  // string sdkVersion = 3;
  if (!this->_internal_sdkversion().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sdkversion().data(), static_cast<int>(this->_internal_sdkversion().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tigeropen.push.pb.Request.Connect.sdkVersion");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_sdkversion(), target);
  }

  // string acceptVersion = 4;
  if (!this->_internal_acceptversion().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_acceptversion().data(), static_cast<int>(this->_internal_acceptversion().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tigeropen.push.pb.Request.Connect.acceptVersion");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_acceptversion(), target);
  }

  // uint32 sendInterval = 5;
  if (this->_internal_sendinterval() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_sendinterval(), target);
  }

  // uint32 receiveInterval = 6;
  if (this->_internal_receiveinterval() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_receiveinterval(), target);
  }

  // bool useFullTick = 7;
  if (this->_internal_usefulltick() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_usefulltick(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tigeropen.push.pb.Request.Connect)
  return target;
}

size_t Request_Connect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tigeropen.push.pb.Request.Connect)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string tigerId = 1;
  if (!this->_internal_tigerid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_tigerid());
  }

  // string sign = 2;
  if (!this->_internal_sign().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sign());
  }

  // string sdkVersion = 3;
  if (!this->_internal_sdkversion().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sdkversion());
  }

  // string acceptVersion = 4;
  if (!this->_internal_acceptversion().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_acceptversion());
  }

  // uint32 sendInterval = 5;
  if (this->_internal_sendinterval() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_sendinterval());
  }

  // uint32 receiveInterval = 6;
  if (this->_internal_receiveinterval() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_receiveinterval());
  }

  // bool useFullTick = 7;
  if (this->_internal_usefulltick() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Request_Connect::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Request_Connect::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Request_Connect::GetClassData() const { return &_class_data_; }


void Request_Connect::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Request_Connect*>(&to_msg);
  auto& from = static_cast<const Request_Connect&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tigeropen.push.pb.Request.Connect)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_tigerid().empty()) {
    _this->_internal_set_tigerid(from._internal_tigerid());
  }
  if (!from._internal_sign().empty()) {
    _this->_internal_set_sign(from._internal_sign());
  }
  if (!from._internal_sdkversion().empty()) {
    _this->_internal_set_sdkversion(from._internal_sdkversion());
  }
  if (!from._internal_acceptversion().empty()) {
    _this->_internal_set_acceptversion(from._internal_acceptversion());
  }
  if (from._internal_sendinterval() != 0) {
    _this->_internal_set_sendinterval(from._internal_sendinterval());
  }
  if (from._internal_receiveinterval() != 0) {
    _this->_internal_set_receiveinterval(from._internal_receiveinterval());
  }
  if (from._internal_usefulltick() != 0) {
    _this->_internal_set_usefulltick(from._internal_usefulltick());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Request_Connect::CopyFrom(const Request_Connect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tigeropen.push.pb.Request.Connect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request_Connect::IsInitialized() const {
  return true;
}

void Request_Connect::InternalSwap(Request_Connect* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.tigerid_, lhs_arena,
      &other->_impl_.tigerid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sign_, lhs_arena,
      &other->_impl_.sign_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sdkversion_, lhs_arena,
      &other->_impl_.sdkversion_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.acceptversion_, lhs_arena,
      &other->_impl_.acceptversion_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Request_Connect, _impl_.usefulltick_)
      + sizeof(Request_Connect::_impl_.usefulltick_)
      - PROTOBUF_FIELD_OFFSET(Request_Connect, _impl_.sendinterval_)>(
          reinterpret_cast<char*>(&_impl_.sendinterval_),
          reinterpret_cast<char*>(&other->_impl_.sendinterval_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Request_Connect::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Request_2eproto_getter, &descriptor_table_Request_2eproto_once,
      file_level_metadata_Request_2eproto[0]);
}

// ===================================================================

class Request_Subscribe::_Internal {
 public:
};

Request_Subscribe::Request_Subscribe(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tigeropen.push.pb.Request.Subscribe)
}
Request_Subscribe::Request_Subscribe(const Request_Subscribe& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Request_Subscribe* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.symbols_){}
    , decltype(_impl_.account_){}
    , decltype(_impl_.market_){}
    , decltype(_impl_.datatype_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.symbols_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbols_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_symbols().empty()) {
    _this->_impl_.symbols_.Set(from._internal_symbols(), 
      _this->GetArenaForAllocation());
  }
  _impl_.account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_account().empty()) {
    _this->_impl_.account_.Set(from._internal_account(), 
      _this->GetArenaForAllocation());
  }
  _impl_.market_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.market_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_market().empty()) {
    _this->_impl_.market_.Set(from._internal_market(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.datatype_ = from._impl_.datatype_;
  // @@protoc_insertion_point(copy_constructor:tigeropen.push.pb.Request.Subscribe)
}

inline void Request_Subscribe::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.symbols_){}
    , decltype(_impl_.account_){}
    , decltype(_impl_.market_){}
    , decltype(_impl_.datatype_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.symbols_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbols_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.market_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.market_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Request_Subscribe::~Request_Subscribe() {
  // @@protoc_insertion_point(destructor:tigeropen.push.pb.Request.Subscribe)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Request_Subscribe::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.symbols_.Destroy();
  _impl_.account_.Destroy();
  _impl_.market_.Destroy();
}

void Request_Subscribe::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Request_Subscribe::Clear() {
// @@protoc_insertion_point(message_clear_start:tigeropen.push.pb.Request.Subscribe)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.symbols_.ClearToEmpty();
  _impl_.account_.ClearToEmpty();
  _impl_.market_.ClearToEmpty();
  _impl_.datatype_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Request_Subscribe::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tigeropen.push.pb.SocketCommon.DataType dataType = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_datatype(static_cast<::tigeropen::push::pb::SocketCommon_DataType>(val));
        } else
          goto handle_unusual;
        continue;
      // string symbols = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_symbols();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tigeropen.push.pb.Request.Subscribe.symbols"));
        } else
          goto handle_unusual;
        continue;
      // string account = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_account();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tigeropen.push.pb.Request.Subscribe.account"));
        } else
          goto handle_unusual;
        continue;
      // string market = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_market();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tigeropen.push.pb.Request.Subscribe.market"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Request_Subscribe::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tigeropen.push.pb.Request.Subscribe)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .tigeropen.push.pb.SocketCommon.DataType dataType = 1;
  if (this->_internal_datatype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_datatype(), target);
  }

  // string symbols = 2;
  if (!this->_internal_symbols().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_symbols().data(), static_cast<int>(this->_internal_symbols().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tigeropen.push.pb.Request.Subscribe.symbols");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_symbols(), target);
  }

  // string account = 3;
  if (!this->_internal_account().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_account().data(), static_cast<int>(this->_internal_account().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tigeropen.push.pb.Request.Subscribe.account");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_account(), target);
  }

  // string market = 4;
  if (!this->_internal_market().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_market().data(), static_cast<int>(this->_internal_market().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tigeropen.push.pb.Request.Subscribe.market");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_market(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tigeropen.push.pb.Request.Subscribe)
  return target;
}

size_t Request_Subscribe::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tigeropen.push.pb.Request.Subscribe)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string symbols = 2;
  if (!this->_internal_symbols().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_symbols());
  }

  // string account = 3;
  if (!this->_internal_account().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_account());
  }

  // string market = 4;
  if (!this->_internal_market().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_market());
  }

  // .tigeropen.push.pb.SocketCommon.DataType dataType = 1;
  if (this->_internal_datatype() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_datatype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Request_Subscribe::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Request_Subscribe::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Request_Subscribe::GetClassData() const { return &_class_data_; }


void Request_Subscribe::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Request_Subscribe*>(&to_msg);
  auto& from = static_cast<const Request_Subscribe&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tigeropen.push.pb.Request.Subscribe)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_symbols().empty()) {
    _this->_internal_set_symbols(from._internal_symbols());
  }
  if (!from._internal_account().empty()) {
    _this->_internal_set_account(from._internal_account());
  }
  if (!from._internal_market().empty()) {
    _this->_internal_set_market(from._internal_market());
  }
  if (from._internal_datatype() != 0) {
    _this->_internal_set_datatype(from._internal_datatype());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Request_Subscribe::CopyFrom(const Request_Subscribe& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tigeropen.push.pb.Request.Subscribe)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request_Subscribe::IsInitialized() const {
  return true;
}

void Request_Subscribe::InternalSwap(Request_Subscribe* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.symbols_, lhs_arena,
      &other->_impl_.symbols_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.account_, lhs_arena,
      &other->_impl_.account_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.market_, lhs_arena,
      &other->_impl_.market_, rhs_arena
  );
  swap(_impl_.datatype_, other->_impl_.datatype_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Request_Subscribe::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Request_2eproto_getter, &descriptor_table_Request_2eproto_once,
      file_level_metadata_Request_2eproto[1]);
}

// ===================================================================

class Request::_Internal {
 public:
  static const ::tigeropen::push::pb::Request_Subscribe& subscribe(const Request* msg);
  static const ::tigeropen::push::pb::Request_Connect& connect(const Request* msg);
};

const ::tigeropen::push::pb::Request_Subscribe&
Request::_Internal::subscribe(const Request* msg) {
  return *msg->_impl_.subscribe_;
}
const ::tigeropen::push::pb::Request_Connect&
Request::_Internal::connect(const Request* msg) {
  return *msg->_impl_.connect_;
}
Request::Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tigeropen.push.pb.Request)
}
Request::Request(const Request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Request* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.subscribe_){nullptr}
    , decltype(_impl_.connect_){nullptr}
    , decltype(_impl_.command_){}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_subscribe()) {
    _this->_impl_.subscribe_ = new ::tigeropen::push::pb::Request_Subscribe(*from._impl_.subscribe_);
  }
  if (from._internal_has_connect()) {
    _this->_impl_.connect_ = new ::tigeropen::push::pb::Request_Connect(*from._impl_.connect_);
  }
  ::memcpy(&_impl_.command_, &from._impl_.command_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.id_) -
    reinterpret_cast<char*>(&_impl_.command_)) + sizeof(_impl_.id_));
  // @@protoc_insertion_point(copy_constructor:tigeropen.push.pb.Request)
}

inline void Request::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.subscribe_){nullptr}
    , decltype(_impl_.connect_){nullptr}
    , decltype(_impl_.command_){0}
    , decltype(_impl_.id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Request::~Request() {
  // @@protoc_insertion_point(destructor:tigeropen.push.pb.Request)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Request::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.subscribe_;
  if (this != internal_default_instance()) delete _impl_.connect_;
}

void Request::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Request::Clear() {
// @@protoc_insertion_point(message_clear_start:tigeropen.push.pb.Request)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.subscribe_ != nullptr) {
    delete _impl_.subscribe_;
  }
  _impl_.subscribe_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.connect_ != nullptr) {
    delete _impl_.connect_;
  }
  _impl_.connect_ = nullptr;
  ::memset(&_impl_.command_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.id_) -
      reinterpret_cast<char*>(&_impl_.command_)) + sizeof(_impl_.id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tigeropen.push.pb.SocketCommon.Command command = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_command(static_cast<::tigeropen::push::pb::SocketCommon_Command>(val));
        } else
          goto handle_unusual;
        continue;
      // uint32 id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tigeropen.push.pb.Request.Subscribe subscribe = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_subscribe(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tigeropen.push.pb.Request.Connect connect = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_connect(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Request::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tigeropen.push.pb.Request)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .tigeropen.push.pb.SocketCommon.Command command = 1;
  if (this->_internal_command() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_command(), target);
  }

  // uint32 id = 2;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_id(), target);
  }

  // .tigeropen.push.pb.Request.Subscribe subscribe = 3;
  if (this->_internal_has_subscribe()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::subscribe(this),
        _Internal::subscribe(this).GetCachedSize(), target, stream);
  }

  // .tigeropen.push.pb.Request.Connect connect = 4;
  if (this->_internal_has_connect()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::connect(this),
        _Internal::connect(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tigeropen.push.pb.Request)
  return target;
}

size_t Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tigeropen.push.pb.Request)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .tigeropen.push.pb.Request.Subscribe subscribe = 3;
  if (this->_internal_has_subscribe()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.subscribe_);
  }

  // .tigeropen.push.pb.Request.Connect connect = 4;
  if (this->_internal_has_connect()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.connect_);
  }

  // .tigeropen.push.pb.SocketCommon.Command command = 1;
  if (this->_internal_command() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_command());
  }

  // uint32 id = 2;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Request::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Request::GetClassData() const { return &_class_data_; }


void Request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Request*>(&to_msg);
  auto& from = static_cast<const Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tigeropen.push.pb.Request)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_subscribe()) {
    _this->_internal_mutable_subscribe()->::tigeropen::push::pb::Request_Subscribe::MergeFrom(
        from._internal_subscribe());
  }
  if (from._internal_has_connect()) {
    _this->_internal_mutable_connect()->::tigeropen::push::pb::Request_Connect::MergeFrom(
        from._internal_connect());
  }
  if (from._internal_command() != 0) {
    _this->_internal_set_command(from._internal_command());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Request::CopyFrom(const Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tigeropen.push.pb.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request::IsInitialized() const {
  return true;
}

void Request::InternalSwap(Request* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Request, _impl_.id_)
      + sizeof(Request::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(Request, _impl_.subscribe_)>(
          reinterpret_cast<char*>(&_impl_.subscribe_),
          reinterpret_cast<char*>(&other->_impl_.subscribe_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Request_2eproto_getter, &descriptor_table_Request_2eproto_once,
      file_level_metadata_Request_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace push
}  // namespace tigeropen
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tigeropen::push::pb::Request_Connect*
Arena::CreateMaybeMessage< ::tigeropen::push::pb::Request_Connect >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tigeropen::push::pb::Request_Connect >(arena);
}
template<> PROTOBUF_NOINLINE ::tigeropen::push::pb::Request_Subscribe*
Arena::CreateMaybeMessage< ::tigeropen::push::pb::Request_Subscribe >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tigeropen::push::pb::Request_Subscribe >(arena);
}
template<> PROTOBUF_NOINLINE ::tigeropen::push::pb::Request*
Arena::CreateMaybeMessage< ::tigeropen::push::pb::Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tigeropen::push::pb::Request >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
