// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TradeTickData.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_TradeTickData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_TradeTickData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_TradeTickData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_TradeTickData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_TradeTickData_2eproto;
namespace tigeropen {
namespace push {
namespace pb {
class TradeTickData;
struct TradeTickDataDefaultTypeInternal;
extern TradeTickDataDefaultTypeInternal _TradeTickData_default_instance_;
class TradeTickData_MergedVol;
struct TradeTickData_MergedVolDefaultTypeInternal;
extern TradeTickData_MergedVolDefaultTypeInternal _TradeTickData_MergedVol_default_instance_;
}  // namespace pb
}  // namespace push
}  // namespace tigeropen
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace tigeropen {
namespace push {
namespace pb {

// ===================================================================


// -------------------------------------------------------------------

class TradeTickData_MergedVol final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tigeropen.push.pb.TradeTickData.MergedVol) */ {
 public:
  inline TradeTickData_MergedVol() : TradeTickData_MergedVol(nullptr) {}
  ~TradeTickData_MergedVol() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TradeTickData_MergedVol(
      ::google::protobuf::internal::ConstantInitialized);

  inline TradeTickData_MergedVol(const TradeTickData_MergedVol& from) : TradeTickData_MergedVol(nullptr, from) {}
  inline TradeTickData_MergedVol(TradeTickData_MergedVol&& from) noexcept
      : TradeTickData_MergedVol(nullptr, std::move(from)) {}
  inline TradeTickData_MergedVol& operator=(const TradeTickData_MergedVol& from) {
    CopyFrom(from);
    return *this;
  }
  inline TradeTickData_MergedVol& operator=(TradeTickData_MergedVol&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TradeTickData_MergedVol& default_instance() {
    return *internal_default_instance();
  }
  static inline const TradeTickData_MergedVol* internal_default_instance() {
    return reinterpret_cast<const TradeTickData_MergedVol*>(
        &_TradeTickData_MergedVol_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TradeTickData_MergedVol& a, TradeTickData_MergedVol& b) { a.Swap(&b); }
  inline void Swap(TradeTickData_MergedVol* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TradeTickData_MergedVol* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TradeTickData_MergedVol* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<TradeTickData_MergedVol>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TradeTickData_MergedVol& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TradeTickData_MergedVol& from) { TradeTickData_MergedVol::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(TradeTickData_MergedVol* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "tigeropen.push.pb.TradeTickData.MergedVol"; }

 protected:
  explicit TradeTickData_MergedVol(::google::protobuf::Arena* arena);
  TradeTickData_MergedVol(::google::protobuf::Arena* arena, const TradeTickData_MergedVol& from);
  TradeTickData_MergedVol(::google::protobuf::Arena* arena, TradeTickData_MergedVol&& from) noexcept
      : TradeTickData_MergedVol(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVolFieldNumber = 2,
    kMergeTimesFieldNumber = 1,
  };
  // repeated int64 vol = 2;
  int vol_size() const;
  private:
  int _internal_vol_size() const;

  public:
  void clear_vol() ;
  ::int64_t vol(int index) const;
  void set_vol(int index, ::int64_t value);
  void add_vol(::int64_t value);
  const ::google::protobuf::RepeatedField<::int64_t>& vol() const;
  ::google::protobuf::RepeatedField<::int64_t>* mutable_vol();

  private:
  const ::google::protobuf::RepeatedField<::int64_t>& _internal_vol() const;
  ::google::protobuf::RepeatedField<::int64_t>* _internal_mutable_vol();

  public:
  // int32 mergeTimes = 1;
  void clear_mergetimes() ;
  ::int32_t mergetimes() const;
  void set_mergetimes(::int32_t value);

  private:
  ::int32_t _internal_mergetimes() const;
  void _internal_set_mergetimes(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:tigeropen.push.pb.TradeTickData.MergedVol)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_TradeTickData_MergedVol_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TradeTickData_MergedVol& from_msg);
    ::google::protobuf::RepeatedField<::int64_t> vol_;
    mutable ::google::protobuf::internal::CachedSize _vol_cached_byte_size_;
    ::int32_t mergetimes_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TradeTickData_2eproto;
};
// -------------------------------------------------------------------

class TradeTickData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tigeropen.push.pb.TradeTickData) */ {
 public:
  inline TradeTickData() : TradeTickData(nullptr) {}
  ~TradeTickData() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TradeTickData(
      ::google::protobuf::internal::ConstantInitialized);

  inline TradeTickData(const TradeTickData& from) : TradeTickData(nullptr, from) {}
  inline TradeTickData(TradeTickData&& from) noexcept
      : TradeTickData(nullptr, std::move(from)) {}
  inline TradeTickData& operator=(const TradeTickData& from) {
    CopyFrom(from);
    return *this;
  }
  inline TradeTickData& operator=(TradeTickData&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TradeTickData& default_instance() {
    return *internal_default_instance();
  }
  static inline const TradeTickData* internal_default_instance() {
    return reinterpret_cast<const TradeTickData*>(
        &_TradeTickData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TradeTickData& a, TradeTickData& b) { a.Swap(&b); }
  inline void Swap(TradeTickData* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TradeTickData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TradeTickData* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<TradeTickData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TradeTickData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TradeTickData& from) { TradeTickData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(TradeTickData* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "tigeropen.push.pb.TradeTickData"; }

 protected:
  explicit TradeTickData(::google::protobuf::Arena* arena);
  TradeTickData(::google::protobuf::Arena* arena, const TradeTickData& from);
  TradeTickData(::google::protobuf::Arena* arena, TradeTickData&& from) noexcept
      : TradeTickData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using MergedVol = TradeTickData_MergedVol;

  // accessors -------------------------------------------------------
  enum : int {
    kTimeFieldNumber = 7,
    kPriceFieldNumber = 8,
    kVolumeFieldNumber = 9,
    kPartCodeFieldNumber = 10,
    kMergedVolsFieldNumber = 14,
    kSymbolFieldNumber = 1,
    kTypeFieldNumber = 2,
    kCondFieldNumber = 3,
    kQuoteLevelFieldNumber = 11,
    kSecTypeFieldNumber = 13,
    kSnFieldNumber = 4,
    kPriceBaseFieldNumber = 5,
    kTimestampFieldNumber = 12,
    kPriceOffsetFieldNumber = 6,
  };
  // repeated int64 time = 7;
  int time_size() const;
  private:
  int _internal_time_size() const;

  public:
  void clear_time() ;
  ::int64_t time(int index) const;
  void set_time(int index, ::int64_t value);
  void add_time(::int64_t value);
  const ::google::protobuf::RepeatedField<::int64_t>& time() const;
  ::google::protobuf::RepeatedField<::int64_t>* mutable_time();

  private:
  const ::google::protobuf::RepeatedField<::int64_t>& _internal_time() const;
  ::google::protobuf::RepeatedField<::int64_t>* _internal_mutable_time();

  public:
  // repeated int64 price = 8;
  int price_size() const;
  private:
  int _internal_price_size() const;

  public:
  void clear_price() ;
  ::int64_t price(int index) const;
  void set_price(int index, ::int64_t value);
  void add_price(::int64_t value);
  const ::google::protobuf::RepeatedField<::int64_t>& price() const;
  ::google::protobuf::RepeatedField<::int64_t>* mutable_price();

  private:
  const ::google::protobuf::RepeatedField<::int64_t>& _internal_price() const;
  ::google::protobuf::RepeatedField<::int64_t>* _internal_mutable_price();

  public:
  // repeated int64 volume = 9;
  int volume_size() const;
  private:
  int _internal_volume_size() const;

  public:
  void clear_volume() ;
  ::int64_t volume(int index) const;
  void set_volume(int index, ::int64_t value);
  void add_volume(::int64_t value);
  const ::google::protobuf::RepeatedField<::int64_t>& volume() const;
  ::google::protobuf::RepeatedField<::int64_t>* mutable_volume();

  private:
  const ::google::protobuf::RepeatedField<::int64_t>& _internal_volume() const;
  ::google::protobuf::RepeatedField<::int64_t>* _internal_mutable_volume();

  public:
  // repeated string partCode = 10;
  int partcode_size() const;
  private:
  int _internal_partcode_size() const;

  public:
  void clear_partcode() ;
  const std::string& partcode(int index) const;
  std::string* mutable_partcode(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_partcode(int index, Arg_&& value, Args_... args);
  std::string* add_partcode();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_partcode(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& partcode() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_partcode();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_partcode() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_partcode();

  public:
  // repeated .tigeropen.push.pb.TradeTickData.MergedVol mergedVols = 14;
  int mergedvols_size() const;
  private:
  int _internal_mergedvols_size() const;

  public:
  void clear_mergedvols() ;
  ::tigeropen::push::pb::TradeTickData_MergedVol* mutable_mergedvols(int index);
  ::google::protobuf::RepeatedPtrField<::tigeropen::push::pb::TradeTickData_MergedVol>* mutable_mergedvols();

  private:
  const ::google::protobuf::RepeatedPtrField<::tigeropen::push::pb::TradeTickData_MergedVol>& _internal_mergedvols() const;
  ::google::protobuf::RepeatedPtrField<::tigeropen::push::pb::TradeTickData_MergedVol>* _internal_mutable_mergedvols();
  public:
  const ::tigeropen::push::pb::TradeTickData_MergedVol& mergedvols(int index) const;
  ::tigeropen::push::pb::TradeTickData_MergedVol* add_mergedvols();
  const ::google::protobuf::RepeatedPtrField<::tigeropen::push::pb::TradeTickData_MergedVol>& mergedvols() const;
  // string symbol = 1;
  void clear_symbol() ;
  const std::string& symbol() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_symbol(Arg_&& arg, Args_... args);
  std::string* mutable_symbol();
  PROTOBUF_NODISCARD std::string* release_symbol();
  void set_allocated_symbol(std::string* value);

  private:
  const std::string& _internal_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(
      const std::string& value);
  std::string* _internal_mutable_symbol();

  public:
  // string type = 2;
  void clear_type() ;
  const std::string& type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* value);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // string cond = 3;
  void clear_cond() ;
  const std::string& cond() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cond(Arg_&& arg, Args_... args);
  std::string* mutable_cond();
  PROTOBUF_NODISCARD std::string* release_cond();
  void set_allocated_cond(std::string* value);

  private:
  const std::string& _internal_cond() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cond(
      const std::string& value);
  std::string* _internal_mutable_cond();

  public:
  // string quoteLevel = 11;
  void clear_quotelevel() ;
  const std::string& quotelevel() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_quotelevel(Arg_&& arg, Args_... args);
  std::string* mutable_quotelevel();
  PROTOBUF_NODISCARD std::string* release_quotelevel();
  void set_allocated_quotelevel(std::string* value);

  private:
  const std::string& _internal_quotelevel() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_quotelevel(
      const std::string& value);
  std::string* _internal_mutable_quotelevel();

  public:
  // string secType = 13;
  void clear_sectype() ;
  const std::string& sectype() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sectype(Arg_&& arg, Args_... args);
  std::string* mutable_sectype();
  PROTOBUF_NODISCARD std::string* release_sectype();
  void set_allocated_sectype(std::string* value);

  private:
  const std::string& _internal_sectype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sectype(
      const std::string& value);
  std::string* _internal_mutable_sectype();

  public:
  // int64 sn = 4;
  void clear_sn() ;
  ::int64_t sn() const;
  void set_sn(::int64_t value);

  private:
  ::int64_t _internal_sn() const;
  void _internal_set_sn(::int64_t value);

  public:
  // int64 priceBase = 5;
  void clear_pricebase() ;
  ::int64_t pricebase() const;
  void set_pricebase(::int64_t value);

  private:
  ::int64_t _internal_pricebase() const;
  void _internal_set_pricebase(::int64_t value);

  public:
  // uint64 timestamp = 12;
  void clear_timestamp() ;
  ::uint64_t timestamp() const;
  void set_timestamp(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(::uint64_t value);

  public:
  // int32 priceOffset = 6;
  void clear_priceoffset() ;
  ::int32_t priceoffset() const;
  void set_priceoffset(::int32_t value);

  private:
  ::int32_t _internal_priceoffset() const;
  void _internal_set_priceoffset(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:tigeropen.push.pb.TradeTickData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 14, 1,
      87, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_TradeTickData_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TradeTickData& from_msg);
    ::google::protobuf::RepeatedField<::int64_t> time_;
    mutable ::google::protobuf::internal::CachedSize _time_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int64_t> price_;
    mutable ::google::protobuf::internal::CachedSize _price_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int64_t> volume_;
    mutable ::google::protobuf::internal::CachedSize _volume_cached_byte_size_;
    ::google::protobuf::RepeatedPtrField<std::string> partcode_;
    ::google::protobuf::RepeatedPtrField< ::tigeropen::push::pb::TradeTickData_MergedVol > mergedvols_;
    ::google::protobuf::internal::ArenaStringPtr symbol_;
    ::google::protobuf::internal::ArenaStringPtr type_;
    ::google::protobuf::internal::ArenaStringPtr cond_;
    ::google::protobuf::internal::ArenaStringPtr quotelevel_;
    ::google::protobuf::internal::ArenaStringPtr sectype_;
    ::int64_t sn_;
    ::int64_t pricebase_;
    ::uint64_t timestamp_;
    ::int32_t priceoffset_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TradeTickData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TradeTickData_MergedVol

// int32 mergeTimes = 1;
inline void TradeTickData_MergedVol::clear_mergetimes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mergetimes_ = 0;
}
inline ::int32_t TradeTickData_MergedVol::mergetimes() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.MergedVol.mergeTimes)
  return _internal_mergetimes();
}
inline void TradeTickData_MergedVol::set_mergetimes(::int32_t value) {
  _internal_set_mergetimes(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.MergedVol.mergeTimes)
}
inline ::int32_t TradeTickData_MergedVol::_internal_mergetimes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mergetimes_;
}
inline void TradeTickData_MergedVol::_internal_set_mergetimes(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mergetimes_ = value;
}

// repeated int64 vol = 2;
inline int TradeTickData_MergedVol::_internal_vol_size() const {
  return _internal_vol().size();
}
inline int TradeTickData_MergedVol::vol_size() const {
  return _internal_vol_size();
}
inline void TradeTickData_MergedVol::clear_vol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vol_.Clear();
}
inline ::int64_t TradeTickData_MergedVol::vol(int index) const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.MergedVol.vol)
  return _internal_vol().Get(index);
}
inline void TradeTickData_MergedVol::set_vol(int index, ::int64_t value) {
  _internal_mutable_vol()->Set(index, value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.MergedVol.vol)
}
inline void TradeTickData_MergedVol::add_vol(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_vol()->Add(value);
  // @@protoc_insertion_point(field_add:tigeropen.push.pb.TradeTickData.MergedVol.vol)
}
inline const ::google::protobuf::RepeatedField<::int64_t>& TradeTickData_MergedVol::vol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tigeropen.push.pb.TradeTickData.MergedVol.vol)
  return _internal_vol();
}
inline ::google::protobuf::RepeatedField<::int64_t>* TradeTickData_MergedVol::mutable_vol()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:tigeropen.push.pb.TradeTickData.MergedVol.vol)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vol();
}
inline const ::google::protobuf::RepeatedField<::int64_t>&
TradeTickData_MergedVol::_internal_vol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vol_;
}
inline ::google::protobuf::RepeatedField<::int64_t>* TradeTickData_MergedVol::_internal_mutable_vol() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vol_;
}

// -------------------------------------------------------------------

// TradeTickData

// string symbol = 1;
inline void TradeTickData::clear_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.ClearToEmpty();
}
inline const std::string& TradeTickData::symbol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.symbol)
  return _internal_symbol();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TradeTickData::set_symbol(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.symbol)
}
inline std::string* TradeTickData::mutable_symbol() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.TradeTickData.symbol)
  return _s;
}
inline const std::string& TradeTickData::_internal_symbol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.symbol_.Get();
}
inline void TradeTickData::_internal_set_symbol(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.Set(value, GetArena());
}
inline std::string* TradeTickData::_internal_mutable_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.symbol_.Mutable( GetArena());
}
inline std::string* TradeTickData::release_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.TradeTickData.symbol)
  return _impl_.symbol_.Release();
}
inline void TradeTickData::set_allocated_symbol(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.symbol_.IsDefault()) {
          _impl_.symbol_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.TradeTickData.symbol)
}

// string type = 2;
inline void TradeTickData::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.ClearToEmpty();
}
inline const std::string& TradeTickData::type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TradeTickData::set_type(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.type)
}
inline std::string* TradeTickData::mutable_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.TradeTickData.type)
  return _s;
}
inline const std::string& TradeTickData::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_.Get();
}
inline void TradeTickData::_internal_set_type(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.Set(value, GetArena());
}
inline std::string* TradeTickData::_internal_mutable_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.type_.Mutable( GetArena());
}
inline std::string* TradeTickData::release_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.TradeTickData.type)
  return _impl_.type_.Release();
}
inline void TradeTickData::set_allocated_type(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.TradeTickData.type)
}

// string cond = 3;
inline void TradeTickData::clear_cond() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cond_.ClearToEmpty();
}
inline const std::string& TradeTickData::cond() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.cond)
  return _internal_cond();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TradeTickData::set_cond(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cond_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.cond)
}
inline std::string* TradeTickData::mutable_cond() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cond();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.TradeTickData.cond)
  return _s;
}
inline const std::string& TradeTickData::_internal_cond() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cond_.Get();
}
inline void TradeTickData::_internal_set_cond(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cond_.Set(value, GetArena());
}
inline std::string* TradeTickData::_internal_mutable_cond() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cond_.Mutable( GetArena());
}
inline std::string* TradeTickData::release_cond() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.TradeTickData.cond)
  return _impl_.cond_.Release();
}
inline void TradeTickData::set_allocated_cond(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cond_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.cond_.IsDefault()) {
          _impl_.cond_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.TradeTickData.cond)
}

// int64 sn = 4;
inline void TradeTickData::clear_sn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sn_ = ::int64_t{0};
}
inline ::int64_t TradeTickData::sn() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.sn)
  return _internal_sn();
}
inline void TradeTickData::set_sn(::int64_t value) {
  _internal_set_sn(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.sn)
}
inline ::int64_t TradeTickData::_internal_sn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sn_;
}
inline void TradeTickData::_internal_set_sn(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sn_ = value;
}

// int64 priceBase = 5;
inline void TradeTickData::clear_pricebase() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pricebase_ = ::int64_t{0};
}
inline ::int64_t TradeTickData::pricebase() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.priceBase)
  return _internal_pricebase();
}
inline void TradeTickData::set_pricebase(::int64_t value) {
  _internal_set_pricebase(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.priceBase)
}
inline ::int64_t TradeTickData::_internal_pricebase() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pricebase_;
}
inline void TradeTickData::_internal_set_pricebase(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pricebase_ = value;
}

// int32 priceOffset = 6;
inline void TradeTickData::clear_priceoffset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.priceoffset_ = 0;
}
inline ::int32_t TradeTickData::priceoffset() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.priceOffset)
  return _internal_priceoffset();
}
inline void TradeTickData::set_priceoffset(::int32_t value) {
  _internal_set_priceoffset(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.priceOffset)
}
inline ::int32_t TradeTickData::_internal_priceoffset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.priceoffset_;
}
inline void TradeTickData::_internal_set_priceoffset(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.priceoffset_ = value;
}

// repeated int64 time = 7;
inline int TradeTickData::_internal_time_size() const {
  return _internal_time().size();
}
inline int TradeTickData::time_size() const {
  return _internal_time_size();
}
inline void TradeTickData::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_.Clear();
}
inline ::int64_t TradeTickData::time(int index) const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.time)
  return _internal_time().Get(index);
}
inline void TradeTickData::set_time(int index, ::int64_t value) {
  _internal_mutable_time()->Set(index, value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.time)
}
inline void TradeTickData::add_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_time()->Add(value);
  // @@protoc_insertion_point(field_add:tigeropen.push.pb.TradeTickData.time)
}
inline const ::google::protobuf::RepeatedField<::int64_t>& TradeTickData::time() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tigeropen.push.pb.TradeTickData.time)
  return _internal_time();
}
inline ::google::protobuf::RepeatedField<::int64_t>* TradeTickData::mutable_time()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:tigeropen.push.pb.TradeTickData.time)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_time();
}
inline const ::google::protobuf::RepeatedField<::int64_t>&
TradeTickData::_internal_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_;
}
inline ::google::protobuf::RepeatedField<::int64_t>* TradeTickData::_internal_mutable_time() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.time_;
}

// repeated int64 price = 8;
inline int TradeTickData::_internal_price_size() const {
  return _internal_price().size();
}
inline int TradeTickData::price_size() const {
  return _internal_price_size();
}
inline void TradeTickData::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_.Clear();
}
inline ::int64_t TradeTickData::price(int index) const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.price)
  return _internal_price().Get(index);
}
inline void TradeTickData::set_price(int index, ::int64_t value) {
  _internal_mutable_price()->Set(index, value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.price)
}
inline void TradeTickData::add_price(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_price()->Add(value);
  // @@protoc_insertion_point(field_add:tigeropen.push.pb.TradeTickData.price)
}
inline const ::google::protobuf::RepeatedField<::int64_t>& TradeTickData::price() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tigeropen.push.pb.TradeTickData.price)
  return _internal_price();
}
inline ::google::protobuf::RepeatedField<::int64_t>* TradeTickData::mutable_price()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:tigeropen.push.pb.TradeTickData.price)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_price();
}
inline const ::google::protobuf::RepeatedField<::int64_t>&
TradeTickData::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline ::google::protobuf::RepeatedField<::int64_t>* TradeTickData::_internal_mutable_price() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.price_;
}

// repeated int64 volume = 9;
inline int TradeTickData::_internal_volume_size() const {
  return _internal_volume().size();
}
inline int TradeTickData::volume_size() const {
  return _internal_volume_size();
}
inline void TradeTickData::clear_volume() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.volume_.Clear();
}
inline ::int64_t TradeTickData::volume(int index) const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.volume)
  return _internal_volume().Get(index);
}
inline void TradeTickData::set_volume(int index, ::int64_t value) {
  _internal_mutable_volume()->Set(index, value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.volume)
}
inline void TradeTickData::add_volume(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_volume()->Add(value);
  // @@protoc_insertion_point(field_add:tigeropen.push.pb.TradeTickData.volume)
}
inline const ::google::protobuf::RepeatedField<::int64_t>& TradeTickData::volume() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tigeropen.push.pb.TradeTickData.volume)
  return _internal_volume();
}
inline ::google::protobuf::RepeatedField<::int64_t>* TradeTickData::mutable_volume()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:tigeropen.push.pb.TradeTickData.volume)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_volume();
}
inline const ::google::protobuf::RepeatedField<::int64_t>&
TradeTickData::_internal_volume() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.volume_;
}
inline ::google::protobuf::RepeatedField<::int64_t>* TradeTickData::_internal_mutable_volume() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.volume_;
}

// repeated string partCode = 10;
inline int TradeTickData::_internal_partcode_size() const {
  return _internal_partcode().size();
}
inline int TradeTickData::partcode_size() const {
  return _internal_partcode_size();
}
inline void TradeTickData::clear_partcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.partcode_.Clear();
}
inline std::string* TradeTickData::add_partcode() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_partcode()->Add();
  // @@protoc_insertion_point(field_add_mutable:tigeropen.push.pb.TradeTickData.partCode)
  return _s;
}
inline const std::string& TradeTickData::partcode(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.partCode)
  return _internal_partcode().Get(index);
}
inline std::string* TradeTickData::mutable_partcode(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.TradeTickData.partCode)
  return _internal_mutable_partcode()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void TradeTickData::set_partcode(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_partcode()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.partCode)
}
template <typename Arg_, typename... Args_>
inline void TradeTickData::add_partcode(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_partcode(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:tigeropen.push.pb.TradeTickData.partCode)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
TradeTickData::partcode() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tigeropen.push.pb.TradeTickData.partCode)
  return _internal_partcode();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
TradeTickData::mutable_partcode() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:tigeropen.push.pb.TradeTickData.partCode)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_partcode();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
TradeTickData::_internal_partcode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.partcode_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
TradeTickData::_internal_mutable_partcode() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.partcode_;
}

// string quoteLevel = 11;
inline void TradeTickData::clear_quotelevel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quotelevel_.ClearToEmpty();
}
inline const std::string& TradeTickData::quotelevel() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.quoteLevel)
  return _internal_quotelevel();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TradeTickData::set_quotelevel(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quotelevel_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.quoteLevel)
}
inline std::string* TradeTickData::mutable_quotelevel() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_quotelevel();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.TradeTickData.quoteLevel)
  return _s;
}
inline const std::string& TradeTickData::_internal_quotelevel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.quotelevel_.Get();
}
inline void TradeTickData::_internal_set_quotelevel(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quotelevel_.Set(value, GetArena());
}
inline std::string* TradeTickData::_internal_mutable_quotelevel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.quotelevel_.Mutable( GetArena());
}
inline std::string* TradeTickData::release_quotelevel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.TradeTickData.quoteLevel)
  return _impl_.quotelevel_.Release();
}
inline void TradeTickData::set_allocated_quotelevel(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quotelevel_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.quotelevel_.IsDefault()) {
          _impl_.quotelevel_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.TradeTickData.quoteLevel)
}

// uint64 timestamp = 12;
inline void TradeTickData::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::uint64_t{0u};
}
inline ::uint64_t TradeTickData::timestamp() const {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.timestamp)
  return _internal_timestamp();
}
inline void TradeTickData::set_timestamp(::uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.timestamp)
}
inline ::uint64_t TradeTickData::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void TradeTickData::_internal_set_timestamp(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// string secType = 13;
inline void TradeTickData::clear_sectype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sectype_.ClearToEmpty();
}
inline const std::string& TradeTickData::sectype() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.secType)
  return _internal_sectype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TradeTickData::set_sectype(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sectype_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:tigeropen.push.pb.TradeTickData.secType)
}
inline std::string* TradeTickData::mutable_sectype() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sectype();
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.TradeTickData.secType)
  return _s;
}
inline const std::string& TradeTickData::_internal_sectype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sectype_.Get();
}
inline void TradeTickData::_internal_set_sectype(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sectype_.Set(value, GetArena());
}
inline std::string* TradeTickData::_internal_mutable_sectype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sectype_.Mutable( GetArena());
}
inline std::string* TradeTickData::release_sectype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:tigeropen.push.pb.TradeTickData.secType)
  return _impl_.sectype_.Release();
}
inline void TradeTickData::set_allocated_sectype(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sectype_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sectype_.IsDefault()) {
          _impl_.sectype_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tigeropen.push.pb.TradeTickData.secType)
}

// repeated .tigeropen.push.pb.TradeTickData.MergedVol mergedVols = 14;
inline int TradeTickData::_internal_mergedvols_size() const {
  return _internal_mergedvols().size();
}
inline int TradeTickData::mergedvols_size() const {
  return _internal_mergedvols_size();
}
inline void TradeTickData::clear_mergedvols() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mergedvols_.Clear();
}
inline ::tigeropen::push::pb::TradeTickData_MergedVol* TradeTickData::mutable_mergedvols(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:tigeropen.push.pb.TradeTickData.mergedVols)
  return _internal_mutable_mergedvols()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::tigeropen::push::pb::TradeTickData_MergedVol>* TradeTickData::mutable_mergedvols()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:tigeropen.push.pb.TradeTickData.mergedVols)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_mergedvols();
}
inline const ::tigeropen::push::pb::TradeTickData_MergedVol& TradeTickData::mergedvols(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tigeropen.push.pb.TradeTickData.mergedVols)
  return _internal_mergedvols().Get(index);
}
inline ::tigeropen::push::pb::TradeTickData_MergedVol* TradeTickData::add_mergedvols() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::tigeropen::push::pb::TradeTickData_MergedVol* _add = _internal_mutable_mergedvols()->Add();
  // @@protoc_insertion_point(field_add:tigeropen.push.pb.TradeTickData.mergedVols)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::tigeropen::push::pb::TradeTickData_MergedVol>& TradeTickData::mergedvols() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tigeropen.push.pb.TradeTickData.mergedVols)
  return _internal_mergedvols();
}
inline const ::google::protobuf::RepeatedPtrField<::tigeropen::push::pb::TradeTickData_MergedVol>&
TradeTickData::_internal_mergedvols() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mergedvols_;
}
inline ::google::protobuf::RepeatedPtrField<::tigeropen::push::pb::TradeTickData_MergedVol>*
TradeTickData::_internal_mutable_mergedvols() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.mergedvols_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace push
}  // namespace tigeropen


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_TradeTickData_2eproto_2epb_2eh
